### ISSUE TITLE
Credit card secure code shouldn't be saved

### ISSUE THREAD

**Issue by r-gaia-cs** [catarse/catarse#1082]

**Comment by diogob** [comment]
True, @devton we should ask the user for the secure code for each new contribution

**Comment by devton** [comment]
@diogob @r-gaia-cs we don't save the credit card secure code, the only that we store is the last four digits and card brand ;)

**Comment by r-gaia-cs** [comment]
> @diogob @r-gaia-cs we don't save the credit card secure code, the only that we store is the last four digits and card brand ;)

Sorry to not be clear at first.

The payment form saved the credit card secure code and suggest it to the user
the next time someone start filling it.

The credit card number don't behave like this and I would like that neither the
credit card secure code.

**Comment by devton** [comment]
@r-gaia-cs oh you are saying about the autocomplete from browser. aggred

**Comment by marceloboeira** [comment]
@devton isn't this a issue for [catarse/catarse_pagarme](https://github.com/catarse/catarse_pagarme) ?

I just created a pl there.

**Comment by devton** [comment]
@marceloboeira thanks ;)
