### ISSUE TITLE
Reward default year should be the automatically calculated

### ISSUE THREAD

**Issue by r-gaia-cs** [catarse/catarse#1102]
Since we know the start and end date of the campaign, we can use it to calculate the default year for the reward be delivery.

## Examples

1. Starting on January 1st 2015 and Ending on January 30th 2015

  Default reward delivery year: 2015
2. Starting on December 2st 2015 and Ending on December 31th 2015

  Default reward delivery year: 2016

**Comment by devton** [comment]
@r-gaia-cs thanks! ;)
