### ISSUE TITLE
Stuck on db:migrate

### ISSUE THREAD

**Issue by darkedge3** [catarse/catarse#1117]
I get the following, and not sure what to do ! Thanks

catarse]# rake db:migrate
/usr/local/rvm/gems/ruby-2.1.5/gems/catarse_paypal_express-2.2.4/lib/catarse_paypal_express/gateway.rb:3:in `<class:Gateway>': Integrations have been extracted into a separate gem (https://github.com/Shopify/offsite_payments) and will no longer be loaded by ActiveMerchant 2.x.
/usr/local/rvm/gems/ruby-2.1.5/gems/active_utils-2.2.3/lib/active_utils/common/country.rb:65: warning: already initialized constant ActiveMerchant::Country::COUNTRIES
/usr/local/rvm/gems/ruby-2.1.5/gems/activemerchant-1.44.1/lib/active_merchant/country.rb:62: warning: previous definition of COUNTRIES was here
rake aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - 
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application/configuration.rb:105:in `database_configuration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.9/lib/active_record/railtie.rb:126:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.9/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
/var/www/vhosts/funder.org.uk/httpdocs/new/catarse/config/environment.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Could not load database configuration. No such file - 
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application/configuration.rb:105:in `database_configuration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.9/lib/active_record/railtie.rb:126:in `block (2 levels) in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.1.9/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
/var/www/vhosts/funder.org.uk/httpdocs/new/catarse/config/environment.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by BeyondTheBoundary** [comment]
I wonder this program still be maintained or not. =.=

**Comment by devton** [comment]
Beyond
to solve the error ExecJS::RuntimeUnavailable: Could not find a JavaScript
runtime  you need to install node

if you are using ubuntu try

sudo apt-get install nodejs

or osx you can run

brew install nodejs





Em Sat Feb 14 2015 at 1:47:55 PM, BeyondTheBoundary <
notifications@github.com> escreveu:
