### ISSUE TITLE
compelte user record visible in div.main_content user-data attribute

### ISSUE THREAD

**Issue by joshblour** [catarse/catarse#1133]
I can see my entire user record, including various authentication tokens by inspecting the html and looking at the div.main_content.

````ruby
.content[data-controller-class=controller.class.name.downcase 
data-controller-name=controller.controller_name.downcase data-action=controller.action_name.downcase 
data-locale="#{I18n.locale}" 
data-user="#{current_user.to_json}"]= yield
````

I'm not sure if this was intentional or not, so I thought I would bring it to your attention.

**Comment by marceloboeira** [comment]
@joshblour can you describe the steps to reproduce this behavior?

**Comment by joshblour** [comment]
Sure. Just login and go to http://www.catarse.me/pt/projects. Then inspect the HTML on the page and search for a div with id #main_content. You can see the user record in data-user

**Comment by devton** [comment]
@joshblour this is a normal behavior, but this only happens for the current user logged in, and we don't show up all info, just a necessary to some scripts works ;)

**Comment by joshblour** [comment]
ok great!  thanks for the project btw, it's fantastic
