### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by darkedge3** [catarse/catarse#1134]
Hi, I'm on Centos and having a couple of issues

**First** when I'm running bundle install on a non-root user, I get this:
```
Errno::EACCES: Permission denied @ rb_sysopen - best_in_place-3.0.0.alpha.gem
An error occurred while installing best_in_place (3.0.0.alpha), and Bundler cannot continue.
Make sure that `gem install best_in_place -v '3.0.0.alpha'` succeeds before bundling.
```

But if I run it with root, I don't get the error.

*however* It does appear that I have successfully installed the gem as follows:

```
catarse]# gem install best_in_place
Successfully installed best_in_place-3.0.3
Parsing documentation for best_in_place-3.0.3
Done installing documentation for best_in_place after 0 seconds
1 gem installed
```

**Second** when I run the database create command, I'm getting authentication failed, whether I use the postgres user, or a different user that I create, and not sure what I'm doing wrong (unless its because I have tried doing that having done bundle install with root user?

Thanks!

**Comment by devton** [comment]
@darkedge3 You change the database configuration on config/database.yml ?

**Comment by darkedge3** [comment]
Yup!!

On Saturday, 14 March 2015, Antônio Roberto Silva <notifications@github.com>
wrote:

> @darkedge3 <https://github.com/darkedge3> You change the database
> configuration on config/database.yml ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catarse/catarse/issues/1134#issuecomment-80700922>.
>


-- 
Sent from Gmail Mobile

**Comment by darkedge3** [comment]
I still have "Ident authentication failed for user" when running rake install :(

**Comment by devton** [comment]
@darkedge3 sry by delay:

The error persist? If yes, The user that is configured is superuser or have permission to login and create tables?

I would suggest using the last stable release: https://github.com/catarse/catarse/releases/tag/v2.0
