### ISSUE TITLE
[Layout] Grid mismatch

### ISSUE THREAD

**Issue by luizfonseca** [catarse/catarse#1176]
I was visiting a project's page and I noticed that the sidebar doesn't match and different grid widths are used (red line on the image). Was it supposed to be like this? 

![screen shot 2015-02-20 at 1 22 30 pm](https://cloud.githubusercontent.com/assets/249782/6288987/2f93600c-b904-11e4-83b3-dd71277c5ab7.png)

**Comment by thiagocatarse** [comment]
hey @luizfonseca !!!

i was curious here ghosting in github and i found your comment! crazy! 

yep! it is supposed to be like this just in this div! if we have followed the grid in this case we thought that the stats (days, backers, ammount backed) and button would have been to close to the video... so it is a padding-right added to the div... design details ;)

**Comment by luizfonseca** [comment]
Cool cool cool @thiagocatarse! Thanks for the reply! :smile:
