### ISSUE TITLE
Catarse as engine

### ISSUE THREAD

**Issue by marnen** [catarse/catarse#1226]
I know I talked about this on the list a while ago, but I don't think I ever mentioned that the http://github.com/marnen/catarse_full gem is usable as an engine. It's based on an old version of Catarse, but we should be able to update it.

**Comment by devton** [comment]
@marnen nice man! seens that is in a very old version (4k commits) we already got 9k
but we are planning to split catarse in several engines in future.
Thanks :)

**Comment by marnen** [comment]
@devton Is that not the current production version? Or is the "production" Git tag no longer being updated?
