### ISSUE TITLE
Mixpanel Configurations?

### ISSUE THREAD

**Issue by xraywu** [catarse/catarse#1233]
Hi, I am pretty new and am trying to set up an instance on my machine and after installation I found Mixpanel needs to be configured... What steps should I take? I would assume I have to create an account on Mixpanel and get an api key. Where should I make the configuration changes in the app and if I have to do anything with my Mixpanel project? Appreciate the help.

**Comment by devton** [comment]
@xraywu type into rails console -> CatarseSettings[:mixpanel_token] = "MIXPANEL_API_KEY"
