### ISSUE TITLE
localization issue with English

### ISSUE THREAD

**Issue by andrascsibi** [catarse/catarse#1240]
I have set up the dev env locally, but I had trouble with getting English to work properly.

I changed `/config/initializers/locale.rb` to 

    I18n.default_locale = :en

While the pt version works great locally, it breaks in english, for example on http://localhost:3000/en/projects/new I get

    undefined method `values' for #<ActiveSupport::SafeBuffer:0x007fb3366cb920>

**Comment by andbod** [comment]
English version seems not to be up to date, most of the things are working but not everything. 

You should compare the *.pt.yml to *.en.yml, check for differences and adjust the transaltion

**Comment by andrascsibi** [comment]
Thanks for the information. All right, I'll try to fix the english locale and submit a pull request when I'm done.

**Comment by hackandgrow** [comment]
ProduceRun has a working English version at github.com/producerun/produceruncatarse

**Comment by andrascsibi** [comment]
Some Portuguese is hardcoded in templates, see https://github.com/catarse/catarse/blob/master/app/views/catarse_bootstrap/explore/index.html.slim#L116
These should come from translations as well.
This hardcoded text seems harder to solve

**Comment by vicnicius** [comment]
I'm closing this issue as it is dated and related to an older version of our code. We still have a ton of work to do to provide good translation support, though.
