### ISSUE TITLE
Can't connect to Redis

### ISSUE THREAD

**Issue by andrascsibi** [catarse/catarse#1241]
I'm running Catarse locally, I did manage to create a user in the console using [this guide](https://github.com/catarse/catarse/wiki/Creating-first-admin), although it seems like it's not an admin user (admin flag is false, and I can't access /admin routes).

Anyway, on various user pages, eg. http://localhost:3000/pt/users/2-andras-csibi/edit#about_me I get the following error.
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Redis doesn't seem to running. Who is supposed to start it?

**Comment by devton** [comment]
@andrascsibi if you are using OSX u can use homebrew (brew install redis) 
or follow this instructions -> http://redis.io/download#installation

**Comment by andrascsibi** [comment]
Thanks @devton 

Do you think we should include this info in the README as a dependency? Shall I make a pull request with this update?
