### ISSUE TITLE
Heroku  build error Attempted to access a nonexistent database

### ISSUE THREAD

**Issue by oudin** [catarse/catarse#1292]
Hi Guys:

I note sure if someone can help me I'm getting a build error when attempting to deploy on heroku 

       Tasks: TOP => environment

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.

 !     Attempted to access a nonexistent database:

 !     https://devcenter.heroku.com/articles/pre-provision-database

 !

 !     Push rejected, failed to compile Ruby app

**Comment by LeonardoVelarde** [comment]
Were you able to fix it?

**Comment by vineetbadola** [comment]
Guys 

Let me know if any one was able to fix this issue
