### ISSUE TITLE
Is CATARSE compatible to RTL languages?

### ISSUE THREAD

**Issue by perpi** [catarse/catarse#1294]
Is Catarse RTLable via CSS completely?
(What is rtl: https://en.wikipedia.org/wiki/Right-to-left)

**Comment by diogob** [comment]
No one has ever tried to use this with a RTL language AFAIK.

**Comment by perpi** [comment]
And, you don't have any program for it on your roadmap?

Are blocks of theme controlled by CSS fully?

**Comment by vicnicius** [comment]
Hello @perpi, I'm sorry for the late answer here. Themes are controlled exclusively by CSS but we still have issues related to translations overall. Closing the issue as it is dated, but feel free to reopen it if you're still interested in working with the project and providing RTL support.
