### ISSUE TITLE
creating admin user

### ISSUE THREAD

**Issue by andrascsibi** [catarse/catarse#1296]
I've followed these instructions to create my first admin user locally.
https://github.com/catarse/catarse/wiki/Creating-first-admin
I get redirected from /admin/users to the home page

BTW, the user gets created with admin: false flag. I've tried to set `admin:true` but that failed `WARNING: Can't mass-assign protected attributes for User: admin`

How do I create an admin user?

**Comment by oudin** [comment]
I'm having the same issue Is there a default admin user?

**Comment by devton** [comment]
@andrascsibi @oudin ouch, sry about that :(
I missing a admin attribute, already adjusted -> https://github.com/catarse/catarse/wiki/Creating-first-admin
You can update the user to set admin, with something like this:

```ruby
user = User.find_by_email "youadminuser@email.com"
user.admin = true
user.save
```
