### ISSUE TITLE
Error during setup , rake db:migrate , db:seed step

### ISSUE THREAD

**Issue by sbose78** [catarse/catarse#1335]
Postgres version 9.3

while running db:migrate I see this on the last line:
/db/migrate/20121226120921_intial_schema.rb:5 in 'up'
Tasks: TOP => db:migrate

When I run the db:seed step, I see the following in the last line of the console output:

20150408154506 RemoveNotNullFromBank
rake db:migrate to update your database and try again.

On starting the server, I see an internal server error ( which is obvious since the db steps didnt go through ).

development.log file:
https://gist.githubusercontent.com/sbose78/2be183cbaf2bbbaaa3f5/raw/development%20log%20catarse

Could you please provide pointers?

**Comment by adrianob** [comment]
Did you try running rake db:migrate ?

**Comment by adrianob** [comment]
Try using version 9.4 and see if the problem persists.
