### ISSUE TITLE
error creating database with db:create db:migrate db:seed

### ISSUE THREAD

**Issue by cromatom** [catarse/catarse#1348]
i get this error when creating a database pls help

delta@dl380-2:~/catarse$ rake db:create db:migrate db:seed
/usr/local/lib/ruby/gems/2.1.0/gems/catarse_paypal_express-3.0.2/lib/catarse_paypal_express/gateway.rb:3:in `<class:Gateway>': Integrations have been extracted into a separate gem (https://github.com/Shopify/offsite_payments) and will no longer be loaded by ActiveMerchant 2.x.
/usr/local/lib/ruby/gems/2.1.0/gems/active_utils-2.2.3/lib/active_utils/common/country.rb:65: warning: already initialized constant ActiveMerchant::Country::COUNTRIES
/usr/local/lib/ruby/gems/2.1.0/gems/activemerchant-1.44.1/lib/active_merchant/country.rb:62: warning: previous definition of COUNTRIES was here
catarse_development already exists
catarse_test already exists
set_default_options has been deprecated, use set_options
2015-04-14T21:21:43Z 16716 TID-oro8a553o INFO: Sidekiq client with redis options {:url=>"redis://localhost:6379/"}
rake aborted!
SyntaxError: /home/delta/catarse/app/models/project.rb:119: syntax error, unexpected ':', expecting ')'
...me.to_s.gsub('between_','') }": starts_at.to_time.. ends_at....
...                               ^
/home/delta/catarse/app/models/project.rb:119: syntax error, unexpected ')', expecting keyword_end
/home/delta/catarse/app/models/project.rb:251: syntax error, unexpected end-of-input, expecting keyword_end
/home/delta/catarse/config/environment.rb:7:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by adrianob** [comment]
Just commited a fix, see if it works for you now.

**Comment by cromatom** [comment]
everything works now!!! thank you.
