### ISSUE TITLE
paypal payment

### ISSUE THREAD

**Issue by pinak1180** [catarse/catarse#1359]
Hello i am getting

undefined method `project' for nil:NilClass

when i actually click paypal button, i dnt see any log that create entry in Payment model

can you please help me?

**Comment by adrianob** [comment]
Paypal support has been discontinued. You can either use an old version or fix the paypal gem to work with the new payment system. Don't forget to send a PR if you do :)

**Comment by hackandgrow** [comment]
We were getting api errors for PayPal, does the PayPal logic follow similar
gem to Braintree.
Do a know a developer that could built a Braintree payment gateway for us?

Cheers,

Willliam Pattison
ProduceRun
Co-Founder / President

415 12th Avenue SE,
Cedar Rapids, IA 52401
USA Cell: +1 319 640 7002
Email: will@producerun.com

www.producerun.com

Follow my ProduceRun profile.

Will Pattison

**Comment by kubicek** [comment]
@adrianob: which is the latest version working with current paypal gem please?
