### ISSUE TITLE
Error when using catarse production Invalid request: Invalid HTTP format, parsing fails

### ISSUE THREAD

**Issue by cromatom** [catarse/catarse#1371]
trying to switch to production i get this error and ssl protocol error on web browser

Invalid request: Invalid HTTP format, parsing fails.
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `execute'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `parse'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands/server.rb:69:in `start'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:76:in `tap'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:76:in `server'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	/root/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
	bin/rails:4:in `require'
	bin/rails:4:in `<main>'

**Comment by adrianob** [comment]
Production uses ssl on all pages so run your server with ssl enabled, for example:
bundle exec thin start -e production --ssl
