### ISSUE TITLE
NoMethodError in Projects#index 

### ISSUE THREAD

**Issue by hanyelbana** [catarse/catarse#1520]
When I change local to en or fr , I get this error:

NoMethodError in Projects#index

Showing /home/investgr/public_html/investgr/app/views/catarse_bootstrap/projects/index.html.slim where line #12 raised:

undefined method `each' for #<ActiveSupport::SafeBuffer:0x007f6850fdfc90>

             .cd-headline.letters.type
               span = t('.banner_before')     
               span.cd-words-wrapper
     12  ->     - t('.banner_words').each do |index, word|
                   - if index == 0 
                     b.is-visible = word
                   - else

URL: http://investgrow.net/

Thanks

**Comment by adrianob** [comment]
Try adding the missing translations for the languages you want.

**Comment by BJM-Union** [comment]
Hi adrianob, how to add the missing translations? I have met the same problem when I tried to use :en as locale...

**Comment by BJM-Union** [comment]
any guiding document could help me to solve this issue? I would like to contribute some translation. Thanks in advance!

**Comment by adrianob** [comment]
For this case just add the translations you want to projects:index:banner_words.
You can take a look at these commits to see how to implement a new language: https://github.com/catarse/catarse/commits?author=dalink
