### ISSUE TITLE
Hey, could you just confirm the installation notes are updated?

### ISSUE THREAD

**Issue by mths0x5f** [catarse/catarse#1572]
I'm have no experience on Ruby on Rails at all, but my boss asked me to research and try some open source crowdfunding tools... I wouldn't work on code base, but simply test Catarse and make a report about it.

The problem is, I can't get it running. Even following the tutorial on Read-me or the other in wiki.

**Comment by diogob** [comment]
The README should be working. Could you describe the step where the installation failed and tell a bit more about the output you've got?

**Comment by mths0x5f** [comment]
Sorry for the late reply! 
Actually, I've tried reinstalling from "production" branch (successfully install all dependencies) and now I got this error on browser, just after "rails server":


    ActiveRecord::PendingMigrationError
    Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=development

    Rails.root: /home/matheus/catarse

I've already run "rake db:create db:migrate db:seed" before, so I have no ideia...

**Comment by diogob** [comment]
If your database is up to date you should not get the message PendingMigrationError.
It seems that your migrations are not running correctly.
What is the output of ```rake db:migrate``` ?

**Comment by mths0x5f** [comment]
This is the full output: https://gist.githubusercontent.com/mths0x5f/847ff8e1a95cb5061c7d/raw/522b91fda231aac72aee46f69dd71c1a2100de71/gistfile1.txt

**Comment by mths0x5f** [comment]
I'm sorry for taking your time. I figured out that release version 2.0 (tar.gz) works just fine. This is sufficient for me for now.
