### ISSUE TITLE
Create campaigns inplace 

### ISSUE THREAD

**Issue by diff-** [catarse/catarse#1584]
And an idea: [Reaction](Reactioncommerce.com) app has a great idea for adding new products to the eshop: you don't need to involve with fields! It give you a ~published page that you put things there! Take a look at their demo. I can't explain well

**Comment by diogob** [comment]
We had something similar in the past. It turns out that this can be quite counter intuitive for first-timers in the system. Besides it gives you less freedom to create a friendly editing environment.
