### ISSUE TITLE
Transifex.com

### ISSUE THREAD

**Issue by perpi** [catarse/catarse#1585]
Transifex.com is a platform for projects and translators! It's completely free for opensource projects.
Will you create an account on it? It makes it simple to contribute for non-technical user to grow up translations.

**Comment by diogob** [comment]
It seems a nice platform. I'll look into this product.

**Comment by perpi** [comment]
Haven't you made a decision?

**Comment by diogob** [comment]
We are not implementing it in the foreseeable future.
