### ISSUE TITLE
I get error when I run `rails server`

### ISSUE THREAD

**Issue by diff-** [catarse/catarse#1586]
Here's the error that I get: https://gist.github.com/diff-/d1d92f6d0250fa4b874f When I run `rails server`
I asked it on #ruby channel in freenode.net and they just told me: "why on earth are they requiring capybara in development. that doesnt even make sense, given they only include capybara in the test env"

Anyway, My machine: Fedora 22

Here is the way I walked through:

    sudo dnf install postgresql ruby npm nodejs postgresql-contrib
    sudo dnf install ruby-devel.i686 libxml2-devel libcurl-devel
    sudo dnf install postgresql-devel (Or: sudo dnf install /usr/include/libpq-fe.h)

And then, gems:

    gem install bundler
    gem install json -v '1.8.3'
    gem install libxml-ruby -v '2.8.0'
    gem install libxml-ruby -v '2.8.0'
    gem install curb -v '0.8.8'
    gem install pg -v '0.17.1'
    gem install rake
    gem install rails

Finally, I can't open catarse via 127.0.0.1:3000?!
How should I solve the problem?!

I've installed it by this code: `bundle install --deployment --without development test`

**Comment by diogob** [comment]
you should use only bundle install to run in development mode.
