### ISSUE TITLE
Facebook login: "This authorization code has been used"

### ISSUE THREAD

**Issue by Lama-su** [catarse/catarse#1648]
Hey! I have deployed catarse on heroku, everything looks fine, but when I try to log in with Facebook i get the following message "Por favor, corrija os seguintes erros:
Não foi possível autorizar de uma conta de Facebook porque "Invalid credentials".

From heroku logs i get:

"E, [2015-07-26T07:03:32.078560 #28] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
 {"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100}}"

Does anyone has any idea about what is going wrong?
And how i can fix it?

**Comment by devton** [comment]
You need to create an facebook app on developers.facebook.com
and set on OauthProvider model

**Comment by Lama-su** [comment]
Hello devton, thanks for the answer but this does not seem to be the cause of the problem: I have already created the Facebook app and I have already set up the OauthProvider, and they do manage to communicate.

According to Facebook developers staff, the problem "means that your app has exchanged the code for a token already before, but now tries to do so again. Most common reason for that would be a problem with storing the access token internally (so that on the next request, your app still “thinks” it does not have a token), so stuff like the session not working properly is what you should investigate first."
(see here: http://stackoverflow.com/questions/31635059/facebook-login-results-in-this-authorization-code-has-been-used - CBroe is a Facebook developer )

So it seems the problem is in catarse code?
Do you have any idea about how i could try to fix this?

**Comment by devton** [comment]
@Lama-su sorry about delay.

I can't reproduce this error, maybe trying create another facebook app?

[]'s

**Comment by Lama-su** [comment]
Hello devton,
I tried to create a new Facebook app, but it does not work.
I guess there is something wrong (and probably very stupid) in my settings so.
This how i have set my Facebook app (i just put the very basic stuff). Is there anything wrong?


![advanced_setts_1](https://cloud.githubusercontent.com/assets/10477665/9429785/fcb4ffb4-49dc-11e5-9f09-11312a644212.png)
![advanced_setts_2](https://cloud.githubusercontent.com/assets/10477665/9429787/fcbbba98-49dc-11e5-998d-5f215f38f7dc.png)
![advanced_setts_3](https://cloud.githubusercontent.com/assets/10477665/9429786/fcbba580-49dc-11e5-933a-ee5ea55590be.png)
![advanced_setts_4](https://cloud.githubusercontent.com/assets/10477665/9429784/fcb4b61c-49dc-11e5-9115-596d9d7a3984.png)
![basic_1](https://cloud.githubusercontent.com/assets/10477665/9429788/fcbcb8e4-49dc-11e5-918f-8b2678fcaab9.png)
![migrations](https://cloud.githubusercontent.com/assets/10477665/9429789/fcbd52a4-49dc-11e5-8373-86dd143ef355.png)

**Comment by Lama-su** [comment]
and in the application itself, is there anything else that has to be modified, beside the config table?
what is the spec/models/authorizations_spec.rb file? shall I change anything there? how?

**Comment by devton** [comment]
@Lama-su the images are broken

**Comment by Lama-su** [comment]
@devton  Ok.. let's try like this then. Does it work this time?

https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/advanced_setts_1.png
https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/advanced_setts_2.png
https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/advanced_setts_3.png
https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/advanced_setts_4.png
https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/basic_1.png
https://dl.dropboxusercontent.com/u/8198296/catarse_facebook/migrations.png

**Comment by devton** [comment]
@Lama-su not yet, you just can drag and drop the images on github comments, github provides the upload to markdown :)

**Comment by Lama-su** [comment]
@devton 
mm.. that's what I did the first time, and they do not look broken to me..
But the links to my dropbox in the previous message do not work?

Anyway, let's try another time :-)

here the link to the images in github cloud, just in case:
https://cloud.githubusercontent.com/assets/10477665/9524931/d0e7082a-4ce1-11e5-96ab-5f0e8f3e7d59.png
https://cloud.githubusercontent.com/assets/10477665/9524927/d0e31c1a-4ce1-11e5-98d2-209899b48d90.png
https://cloud.githubusercontent.com/assets/10477665/9524930/d0e4f4ea-4ce1-11e5-8ccc-bdf1e682e3cf.png
https://cloud.githubusercontent.com/assets/10477665/9524926/d0e09814-4ce1-11e5-9134-3eca1b9d14c7.png
https://cloud.githubusercontent.com/assets/10477665/9524928/d0e3c7e6-4ce1-11e5-8023-f6696ab2680e.png
https://cloud.githubusercontent.com/assets/10477665/9524929/d0e4cd9e-4ce1-11e5-93d2-1f27204bb436.png


![migrations](https://cloud.githubusercontent.com/assets/10477665/9524931/d0e7082a-4ce1-11e5-96ab-5f0e8f3e7d59.png)
![basic_1](https://cloud.githubusercontent.com/assets/10477665/9524927/d0e31c1a-4ce1-11e5-98d2-209899b48d90.png)
![advanced_setts_4](https://cloud.githubusercontent.com/assets/10477665/9524930/d0e4f4ea-4ce1-11e5-8ccc-bdf1e682e3cf.png)
![advanced_setts_3](https://cloud.githubusercontent.com/assets/10477665/9524926/d0e09814-4ce1-11e5-9134-3eca1b9d14c7.png)
![advanced_setts_2](https://cloud.githubusercontent.com/assets/10477665/9524928/d0e3c7e6-4ce1-11e5-8023-f6696ab2680e.png)
![advanced_setts_1](https://cloud.githubusercontent.com/assets/10477665/9524929/d0e4cd9e-4ce1-11e5-93d2-1f27204bb436.png)

**Comment by devton** [comment]
http://d.pr/i/1gafs images still broken :/ send me at email.

About the file  spec/models/authorizations_spec.rb, this is a spec file, you should not change this file to you settings work.

**Comment by Lama-su** [comment]
Hey devton, not sure you got my email.
Anyway, it is probably more useful also for other people to have it here.
So here are my settings in my Facebook account.
Do you see anything wrong?

---------
menu "advanced"
---------

-native or desktop app? -> no
-deauthorize callback URL -> empty

*App restrictions*
-contains alcohol -> no
-age restriction -> 13+
-social discovery -> yes
-country restricted -> no

*Client OAuth Settings"
-Client OAuth Login -> yes
-Web Oauth Login -> yes
-Force Web auth Reauthentication -> no
-Embedded Browser OAuth Login -> no
-Valid OAuth redirect URIs -> my website root
-Login from Devices -> no

*security*
-Server IP Whitelist -> empty
-Update Settings IP whitelist -> empty
-Update Notification Email -> empty
-Client token -> generated token
-Require App Secret -> no
-Allow API Access to App Settings -> yes
-Require 2-factor reauthorization -> no

*Advertising accounts*
-Authorized Ad Account IDs -> empty

*Analytics for Apps*
-Enable Enhanced Interest Targeting -> yes
-Collect the Apple Advertising Identifier (IDFA) with App Events -> yes

----------
menu "Migrations"
----------
-stream post URL security -> off

**Comment by Lama-su** [comment]
Hey @devton , have you had time to have a look at it? no idea?

**Comment by devton** [comment]
@Lama-su sorry dude I can't figure out what is happening, since we don't store de fb token, when you try login to facebook we request a new code every time just for auth, after this he is discarted.

**Comment by Lama-su** [comment]
@devton ok, thanks anyway. :-D
i'll let you know if i find some solution

**Comment by juliomac** [comment]
@Lama-su Have you find the solution? I am having the sam problem. This started happening after I add SSL and now it points to https rather than  http. Could that be just a coincidence?
