### ISSUE TITLE
Error while creating and seeding the database

### ISSUE THREAD

**Issue by akshayshivpuri** [catarse/catarse#1707]
Hi there,
I followed the steps and when I run create and seed the database, I get a bunch of errors as here https://gist.github.com/akshayshivpuri/351df860c6dd436cf1b8

I'm guessing that this is being caused as I haven't changed anything in the database.yml as I'm unaware of the database username and password. I've a fresh install of postgresql. What do I have to add in the username and pwd field?

**Comment by devton** [comment]
hello @akshayshivpuri this error occours when the rails can't connect with the postgresql server.

I think that you postgresql server is not started.

**Comment by akshayshivpuri** [comment]
Hi @devton Thanks for getting back.
I've downloaded the app from http://postgresapp.com/ and when I click on the elephant icon it says running on port 5432. However when I run http://pgadmin.org/ it doesn't show any running server. How do I troubleshoot?

**Comment by akshayshivpuri** [comment]
Hi @devton I followed the following tutorial to install postgresql http://www.moncefbelyamani.com/how-to-install-postgresql-on-a-mac-with-homebrew-and-lunchy/
And when I try launching postgres using the lunchy gem, i get the following error
https://gist.github.com/akshayshivpuri/f8c349b7613f621eec4f

(P.S: I closed the postgres mac app before trying to initiate postgres using lunchy)

**Comment by devton** [comment]
trey brew info postgresql and get the command at "Or, if you don't want/need launchctl, you can just run:"
try manual start.

About the postgresapp you have followed these steps:
- http://postgresapp.com/documentation/install.html
- http://postgresapp.com/documentation/cli-tools.html

**Comment by akshayshivpuri** [comment]
When I run the following commandy while referring at the "Or, if you don't want/need launchtl msg," I get the following error.

Akshays-MacBook-Pro:catarse akshay$ postgres -D /usr/local/var/postgres
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 34990) running in data directory "/usr/local/var/postgres"?

**Comment by akshayshivpuri** [comment]
Also, when I'm trying to run the postgres app it throws me the following error "There is already a PostgreSQL server running on port 5432". At this point I've already uninstalled the postgres app using brew uninstall postgress and tried uninstalling the postgres mac app. However, when I' again install the postgres and open it, it throws me the same error of already a PostgreSQL server running.

**Comment by akshayshivpuri** [comment]
Looks like, I had to stop the postgresql server using the "$ lunchy stop postgres". I've run the rake command and following happens. 
https://gist.github.com/akshayshivpuri/b4ce13148b3f6cd52a58
Can you tell me what username and password fields need to be added in the config/database.yml file? Should the default values i.e. postgres should be left in the username and password?

**Comment by lerrua** [comment]
@akshayshivpuri if you use postgresapp the username can be `postgres` or your home username with a blank password.

**Comment by akshayshivpuri** [comment]
Tried both. Still not working. I've dropped you a msg on gmail.

**Comment by akshayshivpuri** [comment]
Could you help please?

**Comment by devton** [comment]
@akshayshivpuri you can run at terminal "createuser user -s" (-s to superuser) and use this user at database.yml 

p.s: this command will generate a new user at postgresql without password.
