### ISSUE TITLE
heroku run rake db:migrate fails trying to create roles

### ISSUE THREAD

**Issue by jeremysenn** [catarse/catarse#1720]
When trying to migrate the database for the first time on Heroku with "heroku run rake db:migrate", it fails trying to create roles:

ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create role
CONTEXT:  SQL statement "CREATE ROLE postgrest NOLOGIN"

Since heroku does not allow the creation of roles, what is the best course of action to complete the migrations on heroku?

**Comment by devton** [comment]
@jeremysenn heroku postgres does not support 'CREATE ROLE' statments:
https://devcenter.heroku.com/articles/heroku-postgresql#connection-permissions

Currently we are using RDS to handle with our postgresql server, you can host your database anywhere (we recommend aws if you are using heroku to host the app) and pass via env DATABASE_URL=pgurl

[]'s

**Comment by kcpavan** [comment]
Any updates on this? hosting database in a diffrent server is the only solution?

**Comment by adrianob** [comment]
Or you can use version 2.0(https://github.com/catarse/catarse/tree/v2.0), which doesn't require this.

**Comment by kcpavan** [comment]
Thanks!! @adrianob
