### ISSUE TITLE
Error in rake db:migrate

### ISSUE THREAD

**Issue by Fernandox64** [catarse/catarse#1743]
Hello guys,
I'm in trouble in the migrate this is the error that the terminal shows.
 Any idea to fix...

I'm using ruby 2.2.2
and postgres 9.4

Thank you guys

ALTER TABLE ONLY users
    ADD CONSTRAINT users_primary_user_id_reference FOREIGN KEY (primary_user_id) REFERENCES users(id);

--
-- PostgreSQL database dump complete
--
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
/home/rails/catarse/db/migrate/20121226120921_initial_schema.rb:5:in `up'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/home/rails/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
PG::InsufficientPrivilege: ERROR:  permission denied to create extension "pg_trgm"
HINT:  Must be superuser to create this extension.
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
/home/rails/catarse/db/migrate/20121226120921_initial_schema.rb:5:in `up'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
/home/rails/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/home/rails/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by devton** [comment]
@Fernandox64 this is the entire log? I can't see the error.

**Comment by Fernandox64** [comment]
Hi @devton,
When i do rake db:migrate the terminal shows the errors... 
Just pasted text above

**Comment by devton** [comment]
found -> ERROR: permission denied to create extension "pg_trgm" HINT: Must be superuser to create this extension.

You user need to be superuser, when you are creating the user you can pass -s option to turn to superuser.

**Comment by Fernandox64** [comment]
Thank's @devton your tip solved my problem.
I just made the log in postgres and do this comands:
postgres=# \du # to list all users
postgres=# ALTER ROLE user CREATEROLE SUPERUSER;
ALTER ROLE # this was the result
Thank you for answering me so fast...  : )

**Comment by devton** [comment]
:)

**Comment by Hojalab** [comment]
worked for me too thanks
