### ISSUE TITLE
Routing issue once sending first project

### ISSUE THREAD

**Issue by tbly** [catarse/catarse#1746]
Hi All,

I've just tried to install catarse on Ubuntu 14, following the instructions on Catarse guide. Everything looks fine. I can start a Rails server then login with an admin user.

However when I tried to send a first project, after made a draft project on db, then auto forward to edit page, I saw many routing errors as below and got all tabs with blank content:

Started GET "/en/projects/2000/null/project_details?project_id=eq.2000" for 192.168.1.100 at 2015-09-13 16:35:46 +0700
ActionController::RoutingError (No route matches [GET] "/en/projects/2000/null/project_details")

Started GET "/en/projects/2000/null/project_contributions_per_day?project_id=eq.2000" for 192.168.1.100 at 2015-09-13 16:35:46 +0700
ActionController::RoutingError (No route matches [GET] "/en/projects/2000/null/project_contributions_per_day")

It seems something wrong on my installation and getting the route with /null/ but I could not know which issue is, have investigated through the code a long time with no luck.

Could you please help?

Thanks,
Bang

**Comment by tbly** [comment]
It seems I need to setup for API host, found the issue causeing by missing content on meta tag id api-host. 

But I dont know how to do that, also not found anything mentioned about it. Could you please help?

Very appreciate,
Bang

**Comment by diogob** [comment]
@tbly I sugest using the stable version (pre-api).
The last version as a monolithic rails app is 2.0: https://github.com/catarse/catarse/releases/tag/v2.0

**Comment by tbly** [comment]
big thanks
