### ISSUE TITLE
How to configure the database in production mode?

### ISSUE THREAD

**Issue by JulianSkz** [catarse/catarse#1772]
hi i am trying to upload the application to heroku, my knowledge of ruby on rails ​​are very basic. Executing "RAILS_ENV = production bundle exec rake asseets: precompile" I get an error:
How to configure the database in production mode? Thank you

rake aborted!
ActiveRecord::AdapterNotSpecified: 'production' database is not configured. Available: ["development", "test"]
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/connection_adapters/connection_specification.rb:257:in `resolve_symbol_connection'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/connection_adapters/connection_specification.rb:224:in `resolve_connection'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/connection_adapters/connection_specification.rb:152:in `resolve'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/connection_adapters/connection_specification.rb:182:in `spec'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.13/lib/active_record/railtie.rb:127:in `block (2 levels) in <class:Railtie>'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.13/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.13/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/julian/.rvm/gems/ruby-2.2.2/gems/activesupport-
.........

**Comment by devton** [comment]
@JulianSkz o/ you don't need to run assets precompile when you are deploying to heroku he already handles with this for u
