### ISSUE TITLE
/projects?near_me API request is fails

### ISSUE THREAD

**Issue by ArnisL** [catarse/catarse#1783]
Managed to setup API, but there's still one xhr request that fails:

```
Remote Address:127.0.0.1:3001
Request URL:http://localhost:3001/projects?near_me=eq.true&state=eq.online
Request Method:GET
Status Code:400 Bad Request
```

Response:
```
{"hint":null,"details":null,"code":"42703",  
"message":"column projects.near_me does not exist"}
```

I think this migration has broken it:

db/migrate/20150923165654_fix_near_me_function.rb
```
class FixNearMeFunction < ActiveRecord::Migration
  def change
    execute "
        CREATE OR REPLACE FUNCTION public.near_me(\"1\".projects)
         RETURNS boolean
         LANGUAGE sql
         STABLE SECURITY DEFINER
        AS $function$
          SELECT 
      COALESCE($1.state_acronym, 
        (SELECT pa.address_state FROM project_accounts pa 
          WHERE pa.project_id = $1.project_id)) = 
            (SELECT u.address_state FROM users u  
               WHERE u.id = nullif(current_setting('user_vars.user_id'), '')::int)
        $function$
      "
  end
end
````

**Comment by diogob** [comment]
The API version is quite unstable. I would recommend using the release 2.0: https://github.com/catarse/catarse/releases

But we will rewrite the migrations soon to fix this kind of issue

**Comment by ArnisL** [comment]
I'm aware that it's unstable. That's ok

Just giving heads up on issues I face with a fresh look

**Comment by devton** [comment]
@ArnisL already fixed :)

**Comment by ACPK** [comment]
@ArnisL - Since we're setting the state, how would you prevent people from seeing draft projects?

**Comment by ArnisL** [comment]
@ACPK I don't even remember what catarse project is about
