### ISSUE TITLE
Where is setting for catarse api?

### ISSUE THREAD

**Issue by kostyanych77** [catarse/catarse#1784]
I want change url for catarse api. Now i have this:

> Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/null/projects?recommended=eq.true&state=eq.online Failed to load resource: the server responded with a status of 404 (Not Found)
> http://localhost:3000/null/projects?online_date=gte.2015-09-26&state=eq.online Failed to load resource: the server responded with a status of 404 (Not Found)
> http://localhost:3000/null/projects?expires_at=lte.2015-10-15&state=eq.online Failed to load resource: the server responded with a status of 404 (Not Found)

P.S. I start https://github.com/begriffs/postgrest

**Comment by devton** [comment]
hello @kostyanych77 I sugest using the stable version (pre-api).
The last version as a monolithic rails app is 2.0: https://github.com/catarse/catarse/releases/tag/v2.0

I think that this error occours because you don't have created the postgrest database user, try:
```
createuser postgres -S
```

**Comment by kostyanych77** [comment]
Thank you.
