### ISSUE TITLE
Sprockets::FileNotFound at / couldn't find file 'mithril'

### ISSUE THREAD

**Issue by fx2ztqx** [catarse/catarse#1792]
Sprockets::FileNotFound at /
couldn't find file 'mithril'
  (in /Users/Gleb/Sites/catarse/app/assets/javascripts/api/application.js:1)

#<Class:0x007f8587bcdfe0>#_app_views_catarse_bootstrap_projects_index_html_slim__33931527309938630_70105742065720
app/views/catarse_bootstrap/projects/index.html.slim, line 23

18    .w-row
19      .w-col.w-col-4.w-col-push-4
20        a.btn.btn-large.u-marginbottom-10 href="#{hello_path(ref: 'home_banner')}" Saiba mais
21
22 #project-index-root
23 <b>= javascript_include_tag 'api/application'</b>
24
25 section#blog.section-large.bg-gray.before-footer
26  .w-container
27    .u-text-center
28      = link_to CatarseSettings[:blog_url], target: :blank do

**Comment by devton** [comment]
@fx2ztqx  I sugest using the stable version (pre-api).
The last version as a monolithic rails app is 2.0: https://github.com/catarse/catarse/releases/tag/v2.0

About this error you need to run:

```
npm install
bower install
```

npm requires node.js installed
