### ISSUE TITLE
Redis is not listed in dependencies

### ISSUE THREAD

**Issue by hallison** [catarse/catarse#1795]
Please,

Add the Redis server in the list of dependencies.

When try install, following the installation instructions in the README file, I don't can execute `rake db:migrate db:seed`.

    sudo apt-get install postgresql postgresql-contrib
    # PostgreSQL configuration
    su -
    su - postgresql
    createuser -P catarse
    createdb -E utf8 -U catarse catarsedb
 
    git clone https://github.com/catarse/catarse.git
    cd catarse
    cp config/database.sample.yml config/database.yml
    vim config/database.yml
    # ... database configuration
    bundle install
    rake db:migrate db:seed
    # Error sidekiq ...

Not works.

Maybe because the Redis server is not installed in my PC.

Thanks.

**Comment by adrianob** [comment]
There is a more up-to-date readme here: https://github.com/catarse/catarse/wiki/Installing-on-OS-X(El-Capitan)
It should be easy to adapt this to linux, tell me how it goes ;)

**Comment by hallison** [comment]
@adrianob, o problema está na descrição do processo de instalação. Eu li essa página do Wiki. O Redis deveria estar na lista de dependências da página de apresentação do projeto e não em um Wiki de instalação de um sistema operacional específico como o OS X. :)

Continuarei a instalação.

**Comment by hallison** [comment]
@adrianob, o Sidekiq não precisa necessariamente do servidor Redis. Inclui uma _role_ de _superuser_ para o usuário e funcionou. Contudo, há um erro no `db/migrate/20150729110132_add_team_members_view.rb`

    ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
    LINE 55:             FILTER (WHERE c.was_confirmed)
