### ISSUE TITLE
Questions about catarse

### ISSUE THREAD

**Issue by prokopsimek** [catarse/catarse#1811]
Hello, I have few questions about catarse before start of using it.

* Can I change currency in app?
* Is supported multi-currency?
* How to participate in translation? I'd like to translate it into Czech language, when I start to using it.
* Is supported multilanguage?

Thanks for replies

**Comment by devton** [comment]
hello @prokopsimek 

- The currency is not fixed, you can define when you are making a payment via payment gateway integrations;
- No;
- Currently our translations is on config/locates/*.yml files, you can just fork and send us a PR
- Yep, but need translations.

**Comment by prokopsimek** [comment]
thx :)
