### ISSUE TITLE
Running in production with Nginx : "/pt/login" -> 404

### ISSUE THREAD

**Issue by rdupz** [catarse/catarse#1846]
Hello,

Running catarse in production mode, I get this trying to login:
```
Started GET "/pt/login" for 127.0.0.1 at 2015-10-25 12:41:17 +0100
Processing by Devise::SessionsController#new as HTML
  Parameters: {"locale"=>"pt"}
  Rendered catarse_bootstrap/devise/shared/_header.html.slim (1.2ms)
  Rendered catarse_bootstrap/devise/sessions/new.html.slim within layouts/catarse_bootstrap (7.3ms)
  Rendered catarse_bootstrap/devise/shared/_header.html.slim (0.6ms)
  Rendered catarse_bootstrap/errors/not_found.html.slim within layouts/catarse_bootstrap (1.1ms)
  Rendered catarse_bootstrap/layouts/_vwo.html.slim (0.4ms)
  Rendered catarse_bootstrap/layouts/_mixpanel.html.slim (0.2ms)
  Rendered catarse_bootstrap/layouts/_new_zendesk.html.slim (0.3ms)
  Rendered catarse_bootstrap/layouts/_zendesk_widget.html.slim (0.1ms)
  Rendered catarse_bootstrap/layouts/_facebook_sdk.html.slim (0.2ms)
  Rendered catarse_bootstrap/layouts/_hotjar.html.slim (0.3ms)
  Rendered catarse_bootstrap/layouts/_analytics.html.slim (0.2ms)
  Rendered catarse_bootstrap/layouts/_elevio.html.slim (0.4ms)
Completed 404 Not Found in 23ms (Views: 7.9ms | ActiveRecord: 0.0ms)
```

Here is what I did (on my local machine, after failing running the app on the server): 

* After cloning the repo, I bundle install, bower install.
* I configure nginx with an upstream, [as shown here](https://gist.github.com/rdupz/5c6c0de488c4b0ea30b8).
* I run rails with : `rails s -e production -p 3000`

Please note that the problem **does not appear in dev mode** ; this is why I don't think it is a webserver misconfiguration.

Do you have an idea for this ? While i tried a lot of things (puma, thin, unicorn, passenger, localy and on the remote server, precompiling assets..), I'm still not able to get catarse working properly in production (I don't want to use heroku).

Regards,

**Comment by devton** [comment]
You configured ssl? And base_domain conf?

Em dom, 25 de out de 2015 10:06, rdupz <notifications@github.com> escreveu:

**Comment by rdupz** [comment]
Hi,
>You configured ssl? 

Yes.

>And base_domain con?

Huh..I was not aware about that.
I just replace all the `catarse.me` with my URL (`catarse.local`) in `db/seeds.rb`. Then i did `rake db:seed RAILS_ENV=production`and (maybe useless) `rake db:migrate RAILS_ENV=production`.
Now it's working ; thanks.

**Comment by devton** [comment]
@rdupz fixed?

**Comment by rdupz** [comment]
fixed
