### ISSUE TITLE
Undefined method `name_es'

### ISSUE THREAD

**Issue by JulianSkz** [catarse/catarse#1849]
Hello, I have translated all files ".pt.yml" to Spanish and I have kept with the extension ".es.yml" in their respective directories. Then modify the "locale.rb" file as follows : 
I18n.available_locales = [:es]
I18n.default_locale = :es

I run the local server, and it works fine , but when you click on "explore" shows me the following error:
Screenshot error: http://oi62.tinypic.com/25tutcm.jpg
Console error: http://pasted.co/49603877

I run a migration after modifying files ? Thanks

**Comment by adrianob** [comment]
You need to add a name_es column to the categories table.

**Comment by JulianSkz** [comment]
Thank you! always answer my queries. Add the line:
add_column :categories, :name_es, :string
In 20130211174609_add_name_en_to_categories.rb
and the problem was resolved.
