### ISSUE TITLE
Catarse Admin Pages

### ISSUE THREAD

**Issue by mcometa** [catarse/catarse#1859]
I just want to ask if this is really the admin panel? Am I missing styles because it does not look good, to be honest? A lot of broken things, misaligned elements and other stuff.
<img width="1425" alt="screen shot 2015-11-05 at 2 10 36 am" src="https://cloud.githubusercontent.com/assets/66358/10947362/757ced26-8362-11e5-979b-0f64eadc4b94.png">

**Comment by devton** [comment]
@mcometa yes! :'( this is the admin of 2.0 version.

We are building a new admin using a new API, but is not stable and documented yet.

**Comment by mcometa** [comment]
Wow that was fast!? Thank you very much for replying.

**Comment by hackandgrow** [comment]
Hi @devton @mcometa , Would you share the new API for us all to work on together?

**Comment by devton** [comment]
@hackandgrow you need to install PostgREST before and pointing to you catarse database.

After running you just need to add CatarseSettings[:api_host] and done. 

[]'s

**Comment by hackandgrow** [comment]
Thanks Ton

Willliam Pattison
ProduceRun
Co-Founder / President

415 12th Avenue SE,
Cedar Rapids, IA 52401
USA Cell: +1 319 640 7002
Email: will@producerun.com

www.producerun.com

Follow my ProduceRun profile.

Will Pattison
