### ISSUE TITLE
I get this warning:

### ISSUE THREAD

**Issue by hanyelbana** [catarse/catarse#1862]
I get this warning:

/Users/bestpractice/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json_web_token-0.3.1/lib/json_web_token.rb:36: warning: already initialized constant JWT

/Users/bestpractice/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jwt-1.5.1/lib/jwt/json.rb:2: warning: previous definition of JWT was here

**Comment by devton** [comment]
hey @hanyelbana  I sugest using the stable version (pre-api).
The last version as a monolithic rails app is 2.0: https://github.com/catarse/catarse/releases/tag/v2.0
