### ISSUE TITLE
Paypal configure

### ISSUE THREAD

**Issue by JulianSkz** [catarse/catarse#1898]
Hi, I configured paypal with my credentials
CatarseSettings[:paypal_username] = "my username"
CatarseSettings[:paypal_password] = "my password"
CatarseSettings[:paypal_signature] = "my signature"
but to go to: 
some project -> select a reward -> filling my information -> next
(In selecting the method of payment) no option is displayed !

Thank you!

PD: my paypal account is Premier, no business

**Comment by cassioscabral** [comment]
Same thing on master

**Comment by simzen85** [comment]
@JulianSkz I also have this issue, since you closed this, you found a way to fix it ?
