### ISSUE TITLE
Catarse Cheffile - remote: Repository not found

### ISSUE THREAD

**Issue by mashinista** [catarse/catarse#1928]
fatal: repository not found for three repos. Any suggestions on alternative ones?

cookbook 'git',     github: 'fnichol/chef-git'
cookbook 'set_locale', github: 'chef-cookbooks/chef-postgres-locale', ref: '0.1.1'
cookbook 'oh_my_zsh', github: 'chef-cookbooks/chef-oh-my-zsh', ref: '0.1.0'

**Comment by HisashiQ** [comment]
Hey, I'm also getting an issue after running librarian-chef install: 

Installing apt (1.9.0)
Installing build-essential (1.3.4)
Installing chef_gem (0.0.5)
Installing curl (1.0.0)
Installing firefox (0.0.4)
Installing runit (1.0.4)
Installing git (0.9.0)
remote: Repository not found.
fatal: repository 'https://github.com/fnichol/chef-git/' not found

Any idea where the chef-git repo has moved to? Is it meant to be chef-user? (https://github.com/fnichol/chef-user)
