### ISSUE TITLE
Cannot deploy on Heroku: Sprockets::FileNotFound: couldn't find file 'mithril/mithril.js'

### ISSUE THREAD

**Issue by ngavrish** [catarse/catarse#1970]
rake aborted!
remote:        Sprockets::FileNotFound: couldn't find file 'mithril/mithril.js'
remote:        (in /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/app/assets/javascripts/api/application.js:1)
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:106:in `resolve'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:146:in `require_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:167:in `block in process_directives'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:165:in `each'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:165:in `process_directives'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:99:in `evaluate'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:16:in `initialize'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `new'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
remote:        /tmp/build_9587dd2c1eff1eee1c294876c9d0e6f3/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)

**Comment by diogob** [comment]
To deploy on heroku you will need a custom buildpack:
https://github.com/heroku/heroku-buildpack-multi.git
