### ISSUE TITLE
Cannot deploy on Heroku with tag = v2.0: Sprockets::FileNotFound: couldn't find file 'mithril/mithril.js'

### ISSUE THREAD

**Issue by ngavrish** [catarse/catarse#1971]
When migrating:

ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create role

**Comment by adrianob** [comment]
Heroku postgres plan won't work due to insufficient permissions, we recommend setting up a RDS instance on Amazon.

**Comment by ngavrish** [comment]
Then why you have all that heroku staff? Even heroku deployment doc. I've killed a day trying to resolve that and other things.

**Comment by adrianob** [comment]
You can use heroku with no problems, it's just the database that is not supported.

**Comment by SylvieMorin10** [comment]
Hi

Please, who can say me how to solve this?

Thanks
