### ISSUE TITLE
tag v2.0 rails server fails

### ISSUE THREAD

**Issue by ngavrish** [catarse/catarse#1973]
ERROR:  relation "projects_for_home" does not exist
LINE 5:                WHERE a.attrelid = '"projects_for_home"'::reg...

**Comment by devton** [comment]
hello @ngavrish if you already have run migrations when you have on master, you should rerun database creation again. this relation has been removed on master branch.

**Comment by simplyluke** [comment]
I'm having table issues all over the place on v2.0, which was advised to use due to stability issues with tracking master. 

Why are the database migrations incomplete for the tagged v2.0 and how do we fix that?

**Comment by diogob** [comment]
@simplyluke could you paste the error message you are getting? The migrations should work fine in the v2.0.
