### ISSUE TITLE
Translate to english?

### ISSUE THREAD

**Issue by joedirt70** [catarse/catarse#1994]
I followed https://github.com/catarse/catarse/wiki/Translating-to-English    (updated in 2014)

steps but unfortunately when starting the server it says "en" is not valid, won't even load server. 
I've been following producerun but its not as maintained as much as this, any recommendations?

**Comment by cassioscabral** [comment]
Did you make "en" available ? like this I18n.available_locales = [:pt, :en] in the same file initializers/locale.rb

I changed and got a few errors on the frontend, but it loaded the menu in english just fine. 

I didn't change the files yet, the errors might come from that. But it seems, fine. 

Can you post more about your error ? maybe some screenshot

**Comment by sjmog** [comment]
It might be worth knowing that 'catarse' in English translates literally as 'bunda de gato'. Arguably the logo (which looks a little like a cat's tail) doesn't help. Just if you're thinking about localisation!

**Comment by dissentertainer** [comment]
@cassioscabral Is your note above still the best way to switch to English? I have updated locale.rb, cleared my browser cache and restarted the development server and I still see pages in Portuguese, even if they have translated English versions. My config/initializers/locale.rb is:

```
# set available locales from config/locales files
I18n.available_locales = [:pt, :en]

# set default locale to something other than :en
I18n.default_locale = :en
```

If I remove `:pt` from the list of available locales I get a routing error, for example `No route matches [GET] "/pt/login"`. Is this locale being set somewhere else in the application? I would love to contribute additional English translations if I can get this working.

**Comment by dissentertainer** [comment]
The application controller is correctly setting the default locale prior to all controller actions, but something seems to be inserting `/pt/` into the path of certain links within the application. For example, when loading the root path, the Login button link is to `http://localhost:3000/pt/login` and after logging in the links in the user menu all begin with `http://localhost:3000/pt/`.

I see a number of hard coded paths including 'pt' in `app/assets/javascripts/api/application.js`. That file also includes I18n settings that are set to 'pt'. Could this have something to do with why these links on the application root contain the incorrect locale? The root path of projects#index loads that file.

**Comment by vicnicius** [comment]
@dissentertainer Right now we are moving our front-end logic to [catarse.js](https://github.com/catarse/catarse.js), as part of a migration to a SPA approach. Catarse.js uses all the translations from catarse/catarse and we use [I18n-js](https://github.com/fnando/i18n-js) to accomplish this task. As you noticed, this setting is still hard-coded there, so If you set it to 'en' there it will probably work. 

We still have a lot of work to do to finish our front-end migration so there will be some pitfalls to get things working right now. If that's something you are not willing to deal with right now, you can work on top of our [last monolithic application release](https://github.com/catarse/catarse/releases/tag/v2.0).

**Comment by dissentertainer** [comment]
Thanks for the clarification, @vicnicius. I tried changing 'pt' to 'en' in application.js but that causes a blank page. There's no `#app` div inside of `#application` in the view, so I assume this is due to either some missing translation files downstream or work in progress on the migration. I will try using the monolithic release for now.

**Comment by vicnicius** [comment]
I'll try to take a look at the state of our translations right now and as soon as I have any updates I'll share them in this issue.
