### ISSUE TITLE
Changes on contribution model conflict when integrating master version with old catarse_paypal_express engine 

### ISSUE THREAD

**Issue by cassioscabral** [catarse/catarse#2036]
Hello,

I'm updating the [gem catarse_paypal_express](https://github.com/catarse/catarse_paypal_express) from catarse to work with this new version(master) and until now I got some fixes and it's going well. What I need to know now is what to do in this line(catarse_paypal_express gem) on `app/controllers/catarse_paypal_express/paypal_express_controller.rb`

```ruby 
contribution.update_attributes payment_method: 'PayPal', payment_token: response.token
```

In the new version contribution doesn't have the `payment_method` or `payment_token` anymore, they were removed in this [commit](https://github.com/catarse/catarse/blob/master/db/migrate/20150519172925_remove_old_contribution_fields.rb) on May 19, 2015. So I'm hoping someone knows where should I save this information now. What was the design decision behind this ? just for understanding what to do and the reasons, I'm not judging. 

Appreciate any help

**Comment by cassioscabral** [comment]
@diogob @devton could you look into that, please ?

**Comment by devton** [comment]
Hello @cassioscabral nice hear about it and sorry about delay on answer :)

So we have abstracted the payment details into a Payment model so you need to create a payment for this contribution, you can do something like this:

```ruby
contribution.payments.create(gateway: 'PayPal', gateway_data: response.to_json, payment_method: 'PayPal')
```

and create abstracted methods to get the token on gateway_data json field.

We have change the database struct to separate contribution info and payment info, basicaly we can have more than one payment transaction per contribution.

If you need more details you can contact me via email is on my github profile :)

**Comment by cassioscabral** [comment]
Nice @devton, thanks for answering. I was able to change but it wasn't good. With that information I can fix now. Cheers
