### ISSUE TITLE
An error has occurred, this and all later migrations canceled:  PG::SyntaxError: ERROR:  syntax error at or near "(" LINE 55:             FILTER (WHERE c.was_confirmed)

### ISSUE THREAD

**Issue by loveyhtu21** [catarse/catarse#2052]
When I'm migrating the db this error occured

in this migration 20150729110132_add_team_members_view.rb

**Comment by devton** [comment]
Hello @loveyhtu21 seems that you postgresql version is not 9.4 make sure that you postgresql server is 9.4
