### ISSUE TITLE
Project's Life Cycle

### ISSUE THREAD

**Issue by JulianSkz** [catarse/catarse#2059]
Hello, my question is: I understand that the possible states of a project are as follows: draft, approved, in_analysis, deleted, rejected, successful, waiting_funds.... But I do not understand when a project goes online state to successful state for example. 
I'm running tests, and a project that has exceeded its target and has completed its continuing term "online" mode. And in the admin project panel I have no choice "successful".

I hope you understand my question. thanks

**Comment by devton** [comment]
Hello @JulianSkz we have a cron task inside lib/tasks/cron.rake thats run every day to change project states :)

**Comment by JulianSkz** [comment]
Thanks, as always devton!
