### ISSUE TITLE
setup difficulties

### ISSUE THREAD

**Issue by marcohgc** [catarse/catarse#2066]
I am facing the following problems after installing ror. I have setup on sserver ruby rails postgsql.

Could you help me?

bundle exec rails console

/var/www/html/catarse/app/models/concerns/project/base_validator.rb:11: warning: previous definition of ON_ONLINE_TO_END_STATES was here
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from require at bin/rails:4)
/usr/local/lib/ruby/gems/2.2.0/gems/railties-4.1.14/lib/rails/application.rb:482:in `validate_secret_key_config!': Missing`secret_token`and`secret_key_base`for 'development' environment, set these values in`config/secrets.yml` (RuntimeError)

**Comment by devton** [comment]
@marcohgc try opening a rails console and run:
```
CatarseSettings[:secret_token] = SecureRandom.hex(64)
CatarseSettings[:secret_key_base] = SecureRandom.hex(64)
```
and try again

**Comment by vicnicius** [comment]
Hello @marcohgc. Were you able to solve this issue?
