### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rmena123** [catarse/catarse#2093]
Can anyone help setup on AWS. I can donate a small price, let me know. Email me: Rmena123 at gmail

**Comment by marcohgc** [comment]
I am also looking for someone to install it and make some several
adjustments in logo, collors and text. marcohgc at gmail.

2016-04-06 14:43 GMT-03:00 rmena123 <notifications@github.com>:

**Comment by givigier** [comment]
@rmena123 I sent you an email. @marcohgc could you please send me an email(gabriel at givigier.com) with job description?
