### ISSUE TITLE
I cannot display the banners

### ISSUE THREAD

**Issue by ferryville** [catarse/catarse#2111]
I succeed to install locally catarse and having troubles to display the banners for project in the home page. In my browser debugging I have the error catarse.js?body=1:4559 Uncaught TypeError: Cannot read property 'projects' of undefined

![capture d ecran 2016-04-24 a 20 37 30](https://cloud.githubusercontent.com/assets/924051/14769629/df30342c-0a5c-11e6-8663-f9ce770f51ad.png)
![capture d ecran 2016-04-24 a 20 19 27](https://cloud.githubusercontent.com/assets/924051/14769632/04755582-0a5d-11e6-94b6-3d39d6c26795.png)

**Comment by devton** [comment]
hello @ferryville we have made a lot of changes on our front-end code on last days, this still happening?

**Comment by ferryville** [comment]
Sorry for the late answer, it is solved thank you a lot:)
