### ISSUE TITLE
Hard time setting up the plataforma on development and production  

### ISSUE THREAD

**Issue by lauroio** [catarse/catarse#2135]
Hi,

I'm having a hard time setting up the catarse on development end production. Can someone walk me through the steps of setting up everything? 

I would pay it forward with development, the plan is to create an integración with Stripe. I've seen a couple of repo, but not an actualize repo to the current stripe versiones. 

Email me at s@setih.com. (:

**Comment by rohitbatra** [comment]
Hey @lauroengineer , Did you find anyone to set up the environment for you?
