### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by shepher** [catarse/catarse#2159]
I got this error after 'bundle exec rails console'

root@ubuntu:~/catarse# bundle exec rails console
/usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands/console.rb:22:in `block in parse_arguments': invalid option: -t (OptionParser::InvalidOption)
        from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands/console.rb:15:in`new'
        from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands/console.rb:15:in `parse_arguments'
        from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:60:in`console'
        from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.2.3/gems/railties-4.1.14/lib/rails/commands.rb:17:in`<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in`<main>'

Can I have a help? Please!

**Comment by vicnicius** [comment]
@shepher were you able to find out what the problem was?
