### ISSUE TITLE
No route matches [GET] "/projects/1/null error on submitting :city_name

### ISSUE THREAD

**Issue by frankiepooh** [catarse/catarse#2218]
Hey team - trying to install the repo on my local and getting this error when attempting to create my first project.  

`
Started GET "/en/projects/1/null" for 127.0.0.1 at 2016-06-29 15:48:08 -0700
ActionController::RoutingError (No route matches [GET] "/en/projects/1/null"):
  actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
`

**Comment by vicnicius** [comment]
Hello, @frankiepooh. I'm sorry for the very late follow up here. Were you able to find the cause of the issue?

**Comment by sushant12** [comment]
@vicnicius I am having the same issue. I have found out that the project controller is missing an edit action. My question is do I have to add code for the edit action or is it going to be fixed in the next push? The live version of the app has that part working just fine.

**Comment by sushant12** [comment]
@frankiepooh change your `default_locale` to `pt` in `config/initializer/locale.rb ` . That seems to fix that issue.
