### ISSUE TITLE
v3.0

### ISSUE THREAD

**Issue by mfonolleda** [catarse/catarse#2231]
Hi,  I was wondering whether there is any timeline for releasing v3.0 of Catarse. 

We are currently working with v2.0 and are looking to go live in mid October. We are interested in the new features (flex) introduced since v2.0 and are considering switching to the latest version of the current branch. However, we are mindful that the current master version may not be stable.

Would you recommend sticking for the time being with v2.0 or wait for the release of v3.0 or simply use the current code on the master branch?

Thanks!
MF

**Comment by vicnicius** [comment]
Hello, @mfonolleda. Sorry for the very late answer here. 

Right now we still have a lot of work to do until getting to a v3.0. We are starting to formalize an official roadmap, but we still don't have any dates or deadlines taking place.

Regarding our master version, it is actually the version we use [in production](https://www.catarse.me), so it is stable. The main issues related to using it would be the lack of docs, specially the ones related to infrastructure and the new architecture we are using, which is considerable new if compared to industry trends. But it comes with lot's of interesting new features and awesome possibilities. 

The choice of which version to use would depend on lot's of aspects like your team profile, the size of your current user base etc, so I couldn't really tell what would be the best option for your specific case right now.
