### ISSUE TITLE
Farsi Translation

### ISSUE THREAD

**Issue by behzadab** [catarse/catarse#2252]
I'm willing to translate Catarse in Farsi. Is it possible to do that? If yes, is there any technical support on that?

**Comment by vicnicius** [comment]
Hello, @behzadab. Sorry for the very late update here. Right now, the support for translations is on an unstable state as we are migrating the whole application to a new architecture. Working with a new translation on our current code would require some considerable technical effort right now. But if you don't want to spend much time on the issue you can always work on top of our [latest monolithic architecture release](https://github.com/catarse/catarse/releases/tag/v2.0). Support for translations should work just fine there.
