### ISSUE TITLE
rake db:migrate erro

### ISSUE THREAD

**Issue by SilasGuimaraes** [catarse/catarse#2279]
Não estou conseguindo executar o rake db:migrate 

![captura de tela de 2016-08-26 14 11 22](https://cloud.githubusercontent.com/assets/16407326/18013941/fa461a56-6b96-11e6-994a-acb61ec1c264.png)

**Comment by devton** [comment]
olá @SilasGuimaraes ta usando o ultimo código?  tenta executar o comando usando ```bundle exec rake db:migrate```

**Comment by vicnicius** [comment]
@SilasGuimaraes fechando a issue aqui. Subi o ambiente do 0 algumas vezes no último mês e parece que está tudo ok. Sinta-se à vontade pra reabrir aqui se continuar tendo problemas. o/
