### ISSUE TITLE
typo in the readme.md

### ISSUE THREAD

**Issue by stellarmagnet** [catarse/catarse#2280]
In this line: "./postgrest postgres://postgrest@localhost/catarse_development -a anonymous --jwt-secret gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C -s 1 -p 3004"

It says "postgrest@localhost"

but it should be "postgres@localhost"  (no t after the s), assuming we are going with the default user in the database.yml file.

**Comment by vicnicius** [comment]
@stellarmagnet thank you for noticing the possible typo and opening an issue, but actually catarse creates an isolated role to the postgrest service, and the service is supposed to use it. So, no typo here.
