### ISSUE TITLE
Project setup : Can't bundle/install Kgio Error on Windows

### ISSUE THREAD

**Issue by zanynik** [catarse/catarse#2307]
bundle install gives this error. See here : http://stackoverflow.com/questions/14483058/cant-bundle-install-kgio-error

**Comment by devton** [comment]
hello @zanynik I recommend to you setup a vm with ubuntu and install.

**Comment by vicnicius** [comment]
Closing this issue. As @devton mentioned, vm's are the best approach to windows development right now. We have a guide to using vagrant and also a docker setup available. If it is still of interest to you @zanynik, feel free to open an issue if you have any problems with those.
