### ISSUE TITLE
How to launch catarse in aws?

### ISSUE THREAD

**Issue by JulianSkz** [catarse/catarse#2318]
Hi I'm a very confused because I have catarse uploaded to my vps, I access with putty and from putty run the "rails s" command, "redis-server" and sidekiq. This was the way they did in locally on my PC. But I think I'm doing it all wrong. and that losing the connection of putty catarse stops working. Could you explain to me a little how should I do to run correctly catarse in aws?

**Comment by devton** [comment]
@JulianSkz We have a staging environment running on aws using dokku.viewdocs.io/dokku/ (is like heroku)

On development you can install the foreman gem and run "foreman start" at profile folder, this will start all rails processes (web, sidekiq, listeners).

You can use docker too https://github.com/catarse/catarse/blob/master/RUNNING_WITH_DOCKER.md

**Comment by JulianSkz** [comment]
Thanks for you answer devton. Ammm i find a "Tmux" and i run from tmux "rails s", "bundle exec sidekiq", its ok? Because this works for me.

**Comment by bonafernando** [comment]
With this:
```
sudo apt-get remove --purge --auto-remove redis-server -y
sudo apt-get install redis-server
```
worked for me.
