### ISSUE TITLE
Erro durante rake rb:migrate

### ISSUE THREAD

**Issue by Silva01** [catarse/catarse#2337]
Galera, alguém já passou por esse tipo de erro ? acontece quanto utilizo o comando rake rb:migrate

/usr/local/lib/ruby/gems/2.3.0/gems/json_web_token-0.3.1/lib/json_web_token.rb:36: warning: already initialized constant JWT
/usr/local/lib/ruby/gems/2.3.0/gems/jwt-1.5.4/lib/jwt/json.rb:3: warning: previous definition of JWT was here
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
== 20150306170412 MigrateContributionsDataToPayments: migrating ===============
-- execute("    INSERT INTO payments (\n      id,\n      contribution_id,\n      state,\n      key,\n      gateway,\n      gateway_id,\n      gateway_fee,\n      gateway_data,\n      payment_method,\n      value,\n      installments,\n      installment_value,\n      created_at,\n      updated_at,\n      paid_at,\n      refused_at,\n      pending_refund_at,\n      refunded_at\n    )\n    SELECT\n      c.id,\n      c.id,\n      CASE c.state\n        WHEN 'pending' THEN 'pending'\n        WHEN 'waiting_confirmation' THEN 'pending'\n        WHEN 'refunded' THEN 'refunded'\n        WHEN 'refunded_and_canceled' THEN 'deleted'\n        WHEN 'requested_refund' THEN 'pending_refund'\n        WHEN 'requested_refund' THEN 'pending_refund'\n        WHEN 'canceled' THEN 'refused'\n        WHEN 'invalid_payment' THEN 'refused'\n        WHEN 'confirmed' THEN 'paid'\n        WHEN 'chargeback' THEN 'chargeback'\n        ELSE c.state\n      END,\n      coalesce(c.key, md5(id::text || current_timestamp::text)),\n      CASE \n        WHEN c.credits THEN 'Credits'\n        WHEN c.payment_method = 'Credits' THEN 'Credits'\n        WHEN c.payment_method = 'PayPal' THEN 'PayPal'\n        WHEN c.payment_method = 'Pagarme' THEN 'Pagarme'\n        ELSE 'MoIP'\n      END,\n      c.payment_id,\n      c.payment_service_fee,\n      '{}',\n      CASE\n        WHEN c.credits OR c.payment_method = 'Credits' THEN 'Creditos'\n        WHEN c.payment_choice IS NULL THEN 'Desconhecido'\n        ELSE c.payment_choice\n      END,\n      c.value,\n      c.installments,\n      COALESCE(c.installment_value, c.value),\n      c.created_at,\n      c.updated_at,\n      c.confirmed_at,\n      c.canceled_at,\n      c.requested_refund_at,\n      c.refunded_at\n    FROM\n      contributions c\n    WHERE\n      c.state <> 'deleted';\n    UPDATE payment_notifications SET payment_id = contribution_id WHERE EXISTS (SELECT true FROM payments p WHERE p.id = payment_notifications.contribution_id);\n    SELECT setval('payments_id_seq', (SELECT max(id) FROM payments));\n")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type date: "{}"
LINE 47:       '{}',
               ^
:     INSERT INTO payments (
      id,
      contribution_id,
      state,
      key,
      gateway,
      gateway_id,
      gateway_fee,
      gateway_data,
      payment_method,
      value,
      installments,
      installment_value,
      created_at,
      updated_at,
      paid_at,
      refused_at,
      pending_refund_at,
      refunded_at
    )
    SELECT
      c.id,
      c.id,
      CASE c.state
        WHEN 'pending' THEN 'pending'
        WHEN 'waiting_confirmation' THEN 'pending'
        WHEN 'refunded' THEN 'refunded'
        WHEN 'refunded_and_canceled' THEN 'deleted'
        WHEN 'requested_refund' THEN 'pending_refund'
        WHEN 'requested_refund' THEN 'pending_refund'
        WHEN 'canceled' THEN 'refused'
        WHEN 'invalid_payment' THEN 'refused'
        WHEN 'confirmed' THEN 'paid'
        WHEN 'chargeback' THEN 'chargeback'
        ELSE c.state
      END,
      coalesce(c.key, md5(id::text || current_timestamp::text)),
      CASE 
        WHEN c.credits THEN 'Credits'
        WHEN c.payment_method = 'Credits' THEN 'Credits'
        WHEN c.payment_method = 'PayPal' THEN 'PayPal'
        WHEN c.payment_method = 'Pagarme' THEN 'Pagarme'
        ELSE 'MoIP'
      END,
      c.payment_id,
      c.payment_service_fee,
      '{}',
      CASE
        WHEN c.credits OR c.payment_method = 'Credits' THEN 'Creditos'
        WHEN c.payment_choice IS NULL THEN 'Desconhecido'
        ELSE c.payment_choice
      END,
      c.value,
      c.installments,
      COALESCE(c.installment_value, c.value),
      c.created_at,
      c.updated_at,
      c.confirmed_at,
      c.canceled_at,
      c.requested_refund_at,
      c.refunded_at
    FROM
      contributions c
    WHERE
      c.state <> 'deleted';
    UPDATE payment_notifications SET payment_id = contribution_id WHERE EXISTS (SELECT true FROM payments p WHERE p.id = payment_notifications.contribution_id);
    SELECT setval('payments_id_seq', (SELECT max(id) FROM payments));
/home/vagrant/catarse/db/migrate/20150306170412_migrate_contributions_data_to_payments.rb:3:in `up'
ActiveRecord::StatementInvalid: PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type date: "{}"
LINE 47:       '{}',
               ^
:     INSERT INTO payments (
      id,
      contribution_id,
      state,
      key,
      gateway,
      gateway_id,
      gateway_fee,
      gateway_data,
      payment_method,
      value,
      installments,
      installment_value,
      created_at,
      updated_at,
      paid_at,
      refused_at,
      pending_refund_at,
      refunded_at
    )
    SELECT
      c.id,
      c.id,
      CASE c.state
        WHEN 'pending' THEN 'pending'
        WHEN 'waiting_confirmation' THEN 'pending'
        WHEN 'refunded' THEN 'refunded'
        WHEN 'refunded_and_canceled' THEN 'deleted'
        WHEN 'requested_refund' THEN 'pending_refund'
        WHEN 'requested_refund' THEN 'pending_refund'
        WHEN 'canceled' THEN 'refused'
        WHEN 'invalid_payment' THEN 'refused'
        WHEN 'confirmed' THEN 'paid'
        WHEN 'chargeback' THEN 'chargeback'
        ELSE c.state
      END,
      coalesce(c.key, md5(id::text || current_timestamp::text)),
      CASE 
        WHEN c.credits THEN 'Credits'
        WHEN c.payment_method = 'Credits' THEN 'Credits'
        WHEN c.payment_method = 'PayPal' THEN 'PayPal'
        WHEN c.payment_method = 'Pagarme' THEN 'Pagarme'
        ELSE 'MoIP'
      END,
      c.payment_id,
      c.payment_service_fee,
      '{}',
      CASE
        WHEN c.credits OR c.payment_method = 'Credits' THEN 'Creditos'
        WHEN c.payment_choice IS NULL THEN 'Desconhecido'
        ELSE c.payment_choice
      END,
      c.value,
      c.installments,
      COALESCE(c.installment_value, c.value),
      c.created_at,
      c.updated_at,
      c.confirmed_at,
      c.canceled_at,
      c.requested_refund_at,
      c.refunded_at
    FROM
      contributions c
    WHERE
      c.state <> 'deleted';
    UPDATE payment_notifications SET payment_id = contribution_id WHERE EXISTS (SELECT true FROM payments p WHERE p.id = payment_notifications.contribution_id);
    SELECT setval('payments_id_seq', (SELECT max(id) FROM payments));
/home/vagrant/catarse/db/migrate/20150306170412_migrate_contributions_data_to_payments.rb:3:in `up'
PG::InvalidDatetimeFormat: ERROR:  invalid input syntax for type date: "{}"
LINE 47:       '{}',
               ^
/home/vagrant/catarse/db/migrate/20150306170412_migrate_contributions_data_to_payments.rb:3:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by adrianob** [comment]
Que versão do postgres você está usando?

**Comment by Silva01** [comment]
Estou usando a seguinte versão: psql (PostgreSQL) 9.4.9

**Comment by Silva01** [comment]
Problema resolvido ao atualizar o PostgreSQL para a versão 9.6.
