### ISSUE TITLE
Getting We did not find this address :( error each time visit on user profile

### ISSUE THREAD

**Issue by sho-wtag** [catarse/catarse#2355]
Hi,

I am getting error while each time user profile sections.
![screenshot from 2016-10-20 13-18-46](https://cloud.githubusercontent.com/assets/15027323/19549779/17d2bcbc-96c8-11e6-8bc3-da72bbcb4662.png)

Now i am getting this error. 

![screenshot from 2016-10-20 13-19-55](https://cloud.githubusercontent.com/assets/15027323/19549785/1d22eec6-96c8-11e6-93d4-8ec1e2bbe092.png)

I have followed all the installation instruction but still getting this issue. Also `/pt/users/undefined/edit` is getting undefined. I think it is wrong. Does anyone facing the same problem. 

`Started GET "/pt/users/undefined/edit" for 163.53.151.26 at 2016-10-20 03:19:25 -0400
  ActiveRecord::SchemaMigration Load (1.8ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"undefined", "locale"=>"pt"}
  User Load (2.3ms)  SELECT  "users".* FROM "users"  WHERE "users"."deactivated_at" IS NULL AND "users"."id" = 0  ORDER BY "users"."id" ASC LIMIT 1
  Rendered catarse_bootstrap/devise/shared/_header.html.slim (7.9ms)
  Rendered catarse_bootstrap/errors/not_found.html.slim within layouts/catarse_bootstrap (600.2ms)
  Rendered catarse_bootstrap/layouts/_analytics.html.slim (9.8ms)
  User Load (1.7ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1`

**Comment by devton** [comment]
hi @sho-wtag, you postgREST server is on?

[]'s

**Comment by sho-wtag** [comment]
yes it is on.

**Comment by sho-wtag** [comment]
Any solutions for the problem.

**Comment by devton** [comment]
@sho-wtag you can send a print from browser console?

**Comment by devton** [comment]
@sho-wtag another thing, in ```rails console``` that is the configured ```CatarseSettings[:api_host]```

**Comment by sho-wtag** [comment]
This is the value of `CatarseSettings[:api_host]
`
```
2.3.1 :001 > CatarseSettings[:api_host]
 => "http://localhost:3004"
```

**Comment by sho-wtag** [comment]
Here is the print of browser console. 

![screenshot from 2016-10-20 22-38-30](https://cloud.githubusercontent.com/assets/15027323/19569071/12765302-9716-11e6-97a8-c4fa40610af9.png)

**Comment by adrianob** [comment]
Did you start the postgrest server with the same jwt that is configured on CatarseSettings[:jwt_secret]?

**Comment by sho-wtag** [comment]
@adrianob Here is the CatarseSettings[:jwt_secret] value. 
```
2.3.1 :001 > CatarseSettings[:jwt_secret]
 => "gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C"
```

**Comment by devton** [comment]
@sho-wtag appears that localhost:3004 is not on, when you access localhost:3004 via browser you can see the api index?

**Comment by adrianob** [comment]
Yes but did you pass it to postgrest with the --jwt-secret option?

**Comment by sho-wtag** [comment]
@adrianob yes i did pass --jwt-secret options. 
` ./postgrest postgres://rails:test12345@localhost/catarse_development -a anonymous --jwt-secret gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C -s 1 -p 3004`

**Comment by dikaoru** [comment]
Hello! I have the same error... have you found a solution? and I have PostREST confugurated.
Thanks!

**Comment by vicnicius** [comment]
@dikaoru as @devton said above, it looks like for some reason you are not able to reach localhost:3004. There could be a number of reasons for this kind of problem to happen. 

If postgREST correctly displays the `Listening on port 3004` message, you'll have to look for possible network issues disallowing you to access your localhost 3004 port. The problem could be your firewall or a misconfigured hosts file or many others related. 

With everything working and if postgrest is actually running at your localhost, a simple browser visit to `http://localhost:3004/user_details?id=eq.1` should return at least an empty JSON array, but never a Connection Refused error.

**Comment by dikaoru** [comment]
Thanks, you were right.
I missed some changes in my pg_hba.conf.

**Comment by vicnicius** [comment]
@sho-wtag were you able to fix the issues on your environment?
