### ISSUE TITLE
Add new Gateway

### ISSUE THREAD

**Issue by inax124** [catarse/catarse#2374]
Hello. Is possible add other gateway? I need add mercadopago. https://www.mercadopago.com.ar/developers/es/

**Comment by vicnicius** [comment]
@inax124 it is completely possible to add other gateways to the platform, but currently we only maintain our [pagar.me](https://pagar.me) integration. 

Probably the best path to build a new payment gateway integration would be to fork the [Catarse_pagarme](https://github.com/catarse/catarse_pagarme) gem and try to replace the api there by the one you're trying to implement.

**Comment by inax124** [comment]
Great. Iam developer.. i try intrgrate mercadopago and share with us... you can tell me whats file need modifiy and what colums is updated?

**Comment by vicnicius** [comment]
Kind of difficult to tell, @inax124. It will depend not only on the new gateway's api but also on your business requirements. If you are planning to build an actual clone, you will have to make sure that both apis/services have the same capabilities. Then, you could probably start by replacing all calls to the PagarMe gem by the integration service you are trying to add, and from this work on the issues you will find.
