### ISSUE TITLE
Unable to close the delete box as well as delete the campaign

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2426]
After clicking on the `delete project` a dialogue box appears and if i click on `cancel` nothing seems to happen. After I fill in `delete-draft` and click on `delete`, it seems to stuck there forever.

**Comment by vicnicius** [comment]
We've fixed this issue on the new version of catarse.js. There should probably be a new release of it during this week. Or you can try to use the latest version of [catarse.js](https://github.com/catarse/catarse.js) yourself, if you are familiar with javascript in general.

**Comment by sushant12** [comment]
Thanks @vicnicius
