### ISSUE TITLE
how to install postgresql-contrib when using brew to install postgresql on OSX

### ISSUE THREAD

**Issue by mikesmayer** [catarse/catarse#2430]
hi,

i'm getting the following error:

PG::SyntaxError: ERROR:  syntax error at or near "PARALLEL"
LINE 12: -- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -

i think this is because I haven't installed postgresql-contrib -- can someone help me understand how to install this. i have installed postgresql on OSX using brew.

from what I can gather, postgresql-contrib, is a collection of modules or is it a specific module?

**Comment by devton** [comment]
hello @mikesmayer i think that is because the version that you have installed, postgres 9.6, try using 9.4, is is your local mac I recommeded to use http://postgresapp.com/

**Comment by mikesmayer** [comment]
thanks! @devton

**Comment by ACPK** [comment]
@devton @ianfleeton  - Were you able to get it working with 9.6?
