### ISSUE TITLE
What do you guys think of adding the pledge amount in the supporters list?

### ISSUE THREAD

**Issue by sushantbajra** [catarse/catarse#2438]
In the supporters tab of campaign project`s page, it would be better if we could show the pledged amount for each supporters.

**Comment by vicnicius** [comment]
Hello, @sushantbajra. This is an issue we have discussed internally with our team and it is really a subjective topic. In our case, we are willing to always communicate that crowdfunding is a way of connecting people more than anything. So anyone that "connected" to that project is equally important. Adding the amount backed would only be a way to differentiate an action we believe is equal in essence.

**Comment by sushantbajra** [comment]
I will be contributing to this project soon.
