### ISSUE TITLE
pg_dump error

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2446]
I am using docker and when I ran `docker-compose run web rake db:migrate` I got this err 

    rake aborted!
    failed to execute:
    pg_dump -s -x -O -f /usr/src/app/db/structure.sql --schema=public --schema=partitioning docker_rails_dev
    
    Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.
    
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/tasks/postgresql_database_tasks.rb:90:in `run_cmd'
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/tasks/postgresql_database_tasks.rb:55:in `structure_dump'
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:183:in `structure_dump'
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:279:in `block (3 levels) in <top (required)>'
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:53:in `block (2 levels) in <top (required)>'
    /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
    Tasks: TOP => db:structure:dump
    (See full trace by running task with --trace)

  [1]: http://pastebin.com/4NmrbYcc
  [2]: http://pastebin.com/GKXuzzEQ

**Comment by sushantbajra** [comment]
any luck here guys???

**Comment by devton** [comment]
@sushant12 @sushantbajra you need install pg_dump program, if you are on linux need to install postgres-contrib package

**Comment by sushant12** [comment]
@devton postgresql-contrib package is installed in my system. I am using docker to run the catarse app. I do not think that having postgresql-contrib package installed in my local system will make any difference.

**Comment by sushantbajra** [comment]
@devton  are you suggesting that I should install postgresql-contrib package inside my catarse container?

**Comment by ikazoy** [comment]
@sushant12 @sushantbajra 
Found a work-around.
Put the code to install postgresql-client package somewhere in `dev.Dockerfile` like this.

```
 RUN set -ex \
   && curl -sL "https://deb.nodesource.com/setup_6.x" | bash - \
   && apt-get -y install nodejs \
   && npm install -g bower

# add apt repository to install 9.5
# ref : https://www.postgresql.org/download/linux/debian/
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  apt-key add -\
  && apt-get update\
  && apt-get -y install postgresql-client-9.5

RUN gem install bundler -v 1.11.2 --no-ri --no-rdoc
```

As @devton suggested, I tried to install pg_dump command which is included in postgres-client package
Firstly, I just did `apt-get install postgresql-client` but encountered this error message.
```
pg_dump: server version: 9.5.1; pg_dump version: 9.4.10
pg_dump: aborting because of server version mismatch
rake aborted!
failed to execute:
pg_dump -s -x -O -f /usr/src/app/db/structure.sql --schema=public --schema=partitioning docker_rails_dev
```
That is why I needed to the additional work. Hope this helps you guys.

Maybe better to make a pull request for the developers using Docker?

**Comment by ACPK** [comment]
@sushantbajra @ikazoy - Did you find a solution for this? I'm happy to make a PR when it's solved.

**Comment by sushant12** [comment]
@ACPK I have stopped using docker for now. It would be cool if you could send a PR

**Comment by sushant12** [comment]
closing, since I am not using docker
