### ISSUE TITLE
Which host did you use for catarse.me?

### ISSUE THREAD

**Issue by drakhshaniaram** [catarse/catarse#2447]
Hi dears, 
I wanna really appreciate your efforts for this giant PERFECT project.
I was wondering if you could give me please some information about the host you used for catarse.me(I mean the space, bandwidth, technologies and other features).

Thanks again.

**Comment by devton** [comment]
hello @drakhshaniaram we used heroku.com to host the production environment
for the staging environment we use one ec2 on aws with dokku (https://github.com/dokku/dokku)

[]'s

**Comment by drakhshaniaram** [comment]
Thank you for answering dear @devton. Actually if you don't mind I need some more details about the plan that you used on heroku.com for your sample website(Hobby, Standard, Premium, etc).

In another word if we want to have a host just like yours, which plan should we use? It will be enough to know how much RAM, capacity, bandwidth and so on did/does it need. 

Would you be kind enough to help us choose? Thanks a million friend.

**Comment by devton** [comment]
@drakhshaniaram currently we use one dyno PX 14gb but you can run on standard dynos

**Comment by drakhshaniaram** [comment]
Thanks an ocean my friend! 
It saved a day for me.

**Comment by devton** [comment]
@drakhshaniaram i forgot to say
if heroku postgres does not create the custom roles for the app you need to use amazon RDS for database
