### ISSUE TITLE
Are slim views being used?

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2448]
I was looking at the code and making some tweaks and I found out that catarse is calling mithrill components to render parts of the views like header footer. There are slim views for them as well but are they being used?

**Comment by devton** [comment]
@sushant12 we still using slim for server side rendering and embed mithril components, in some cases you can see that slim views are rendering the metatags and pass some arguments to mithril when needed

**Comment by sushant12** [comment]
gotcha thanks. Do you have any idea when the new catarse platform will be fully migrated?
