### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2449]
I have changed default locale to `en` in `api/application.js`. Then I updated the `en.yml` file to same as `pt.yml ` . Then inside the ` locales/catarse_bootstrap/views/projects/` I create `project.en.yml `file and copied the contents of `project.pt.yml` file. When I ran the project, I get this error on title bar `missing en.projects.home.header_html translation` . Am I missing somethig?

**Comment by sushantbajra** [comment]
If I want to translate then what are the steps to follow? Because it looks like the new yml file are not being read or something.

**Comment by coolitea** [comment]
I also tried to translate to English. But I couldn't make it work yet.

**Comment by sushant12** [comment]
@coolitea catarse is using a gem called i18n-js which turns the yml file into js object. That`s all i know but still i cant get it to work.

**Comment by sushant12** [comment]
@coolitea here is how you can get the translations you added  to work. If you are using translations in slim views then you need to make changes in `config/initializers/locale.rb`  and restart the server.

For mithrill views you need to change the locale to `en` in` app/assets/javascripts/api/application.js` then run  `rake tmp:cache:clear` and start the server. Remember to set locale to `en` in `config/initializers/locale.rb`

**Comment by bastianjoel** [comment]
Any changes on that? The solution of @sushant12 doesn't work anymore.

**Comment by WizardKid** [comment]
The issue I am having is that even though I made the changes to English, it isn’t reflecting on the pages. I translated the pt pages to see if it would change and it didn’t
