### ISSUE TITLE
project image not showing up

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2458]
![crowdfunding e financiamento coletivo no brasil e no catarse](https://cloud.githubusercontent.com/assets/8981250/21960166/933d028e-db08-11e6-8ffd-7a4963188631.png)

I had uploaded card image but it is not showing up in home page. My postgrest server is running on port 3004 and made a get request to /projects and found that project_img is null.

PS: Profile picture and cover images are also not being shown. However, it is showing on pages that uses the slim views

**Comment by vicnicius** [comment]
@sushant12 this is probably because image paths domain is hardcoded on catarse.js. I will take a look and fix it asap.

**Comment by sushant12** [comment]
@vicnicius it would be great if you could tell me which files to make changes to and I will fix that issue

**Comment by vicnicius** [comment]
Hello @sushant12. Just took a closer look at the issue and actually the endpoint is no hardcoded. This project image path is set on the back-end. Currently we upload images to a Amazon S3 instance, so perhaps your problem is with the aws (key + secret) configuration. If it is, you can simply update your settings table with it.

**Comment by sushant12** [comment]
@vicnicius  thanks that worked.Why wasnt I getting the values when I did not specify aws keys?

**Comment by vicnicius** [comment]
@sushant12 as Catarse was designed to run on top of a PaaS infrastructure, there's no concept of a local storage for uploaded resources on it's architecture. You would need to implement your own solution if you are planning to store those images locally.

**Comment by rahul1504013** [comment]
I am facing same problem. I have updated my credentials in settings table but still image is not showing up
