### ISSUE TITLE
Unable to set "Local do projeto" while creating a new project

### ISSUE THREAD

**Issue by nadirali91** [catarse/catarse#2469]
While trying to add a new project, I encountered a problem saving the location of the project.
(everything else was updated successfully except the "Local do projeto".
How can I solve this?

**Comment by sushant12** [comment]
@nadirali91 I encountered the same problem as well. You need to add some data in cities and states table in your database. In your location field, type in what you have saved in your db and it will show you the city in dropdown.

**Comment by nadirali91** [comment]
Thanks, it is working.
