### ISSUE TITLE
/pt/ redirection

### ISSUE THREAD

**Issue by nadirali91** [catarse/catarse#2478]
I have checked all the files for a "/pt/" in the urls, and have deleted it.
Everything worked fine, but now when I try to contribute to a project, I get an url with "/pt/", and it redirects automatically to the homepage.
How can I solve this ?

**Comment by sushant12** [comment]
have u changed the /pt/ url in catarse.js file as well?

**Comment by nadirali91** [comment]
I did, still no luck

**Comment by devton** [comment]
the /pt/ is because the gem routing-filter you need to remove this gem from Gemfile @nadirali91

**Comment by nadirali91** [comment]
Perfect, thank you @devton. It is working now.
