### ISSUE TITLE
postgrest issue

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2486]
I have successfully run postgrest in my aws ec2 instace, however I am unable to fetch data. My nginx conf looks something like this for postgrest

```
http {
  ...
  # upstream configuration
  upstream postgrest {
    server localhost:3004;
    keepalive 64;
  }
  ...
  server {
    ...
    # expose to the outside world
    location /api {
      default_type  application/json;
      proxy_hide_header Content-Location;
      add_header Content-Location  /api$upstream_http_content_location;
      proxy_set_header  Connection "";
      proxy_http_version 1.1;
      proxy_pass http://postgrest/;
    }
    ...
  }
}
```

this is how I am running my postgrest

`./postgrest 'postgres://user:pass@localhost/db' -a anonymous --jwt-secret gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C -s 1 -p 3004`

I have set the `api_host `and `jwt_token` in the `CatarseSettings` as well. When I hit the `domain.com/api` endpoint the postgrest server is logging it however in the network tab of the browser, I see that `domain.com/api_token ` is not found and this is the response `{"hint":null,"details":null,"code":"42P01","message":"relation \"1._token\" does not exist"}`

**Comment by omariano** [comment]
Did you resolve this ?

**Comment by sushant12** [comment]
@omariano  Nope. I stopped using docker. I will open this issue again

**Comment by omariano** [comment]
Try adding  `db-schema    = "public"` to your postgrest config file

**Comment by sushant12** [comment]
@omariano I am using postgrest v 0.3 .

**Comment by sushant12** [comment]
I tried using the new version of postgrest but the catarse app kept failing

**Comment by mikesmayer** [comment]
@sushant12 I think that this is the issue you're encountering: 

https://gitter.im/begriffs/postgrest/archives/2015/09/29

* create role anonymous
    * create role authenticator noinherit login;
* create role anonymous
    * create role anonymous nologin;
* need to grant authentication to anonymous user
    * grant anonymous to authenticator;

**Comment by sushant12** [comment]
sorry I left it like this. This issue is solved. I changed the `location /api` to `location /api/ ` in the nginx conf file. The postgrest repo had a typo. Here is my [PR](https://github.com/begriffs/postgrest-docs/pull/44) for that fix .

After that you have to save the api host in your db like `domain/api` without the `/` after `domain/api` because mithrill-postgrest adds `/<endpoint>` when querying the endpoint.
