### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by drakhshaniaram** [catarse/catarse#2502]
Hi guys.
Could someone please tell me how can I translate the catarse.me to English? What about another languages? Do we have an English version in the code by default? If we do, how can I activate it?

Thanks in advance.

**Comment by sushant12** [comment]
Hi @drakhshaniaram , I have translated the [project](https://github.com/sushant12/jvn) to english however I have updated the project to fit my needs.

**Comment by drakhshaniaram** [comment]
Dear @sushant12 , thanks a million. It will save a day.
