### ISSUE TITLE
I got error when trying run rake db:migrate

### ISSUE THREAD

**Issue by huyngvu** [catarse/catarse#2507]
The error i have is:

== 20150729110132 AddTeamMembersView: migrating ===============================
-- execute("      DO\n      $body$\n        BEGIN\n          IF NOT EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname = 'anonymous') THEN\n            CREATE ROLE anonymous NOLOGIN;\n          END IF;\n        END\n      $body$;\n      CREATE OR REPLACE FUNCTION public.was_confirmed(contributions) RETURNS boolean\n          LANGUAGE sql STABLE SECURITY DEFINER\n          AS $_$\n            SELECT EXISTS (\n              SELECT true\n              FROM\n                payments p\n              WHERE p.contribution_id = $1.id AND p.state = ANY(confirmed_states())\n            );\n          $_$;\n\n      CREATE OR REPLACE FUNCTION public.profile_img_thumbnail(users) RETURNS text AS $$\n      SELECT\n        'https://' || (SELECT value FROM settings WHERE name = 'aws_host') ||\n        '/' || (SELECT value FROM settings WHERE name = 'aws_bucket') ||\n        '/uploads/user/uploaded_image/' || $1.id::text ||\n        '/thumb_avatar_' || $1.uploaded_image\n      $$ LANGUAGE SQL STABLE SECURITY DEFINER;\n\n      CREATE OR REPLACE VIEW \"1\".team_members AS (\n        select\n          u.id,\n          u.name,\n          u.profile_img_thumbnail as img,\n          COALESCE(ut.total_contributed_projects, 0) as total_contributed_projects,\n          COALESCE(ut.sum, 0) as total_amount_contributed\n        from users u\n        left join \"1\".user_totals ut on ut.user_id = u.id\n        where u.admin\n        order by u.name asc\n      );\n\n      GRANT SELECT on \"1\".team_members to admin;\n      GRANT SELECT on \"1\".team_members to web_user;\n      GRANT SELECT on \"1\".team_members to anonymous;\n\n      drop index if exists user_totals_user_id_ix;\n      drop index if exists user_admin_id_ix;\n      create index user_totals_user_id_ix on \"1\".user_totals(user_id);\n      create index user_admin_id_ix on users(id) where admin;\n\n      CREATE OR REPLACE VIEW \"1\".team_totals as (\n        select\n          count(DISTINCT u.id) as member_count,\n          array_to_json(array_agg(DISTINCT country.name)) as countries,\n          count(DISTINCT c.project_id)\n            FILTER (WHERE c.was_confirmed)\n            as total_contributed_projects,\n          count(DISTINCT lower(unaccent(u.address_city))) as total_cities,\n          sum(c.value)\n            FILTER (WHERE c.was_confirmed)\n            as total_amount\n        from users u\n        left join contributions c on c.user_id = u.id\n        left join countries country on country.id = u.country_id\n        where u.admin\n      );\n\n      GRANT SELECT on \"1\".team_totals to admin;\n      GRANT SELECT on \"1\".team_totals to web_user;\n      GRANT SELECT on \"1\".team_totals to anonymous;\n")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "("
LINE 55:             FILTER (WHERE c.was_confirmed)
                            ^
:       DO
      $body$
        BEGIN
          IF NOT EXISTS (SELECT * FROM pg_catalog.pg_roles WHERE rolname = 'anonymous') THEN
            CREATE ROLE anonymous NOLOGIN;
          END IF;
        END
      $body$;

**Comment by sushant12** [comment]
what is your postgres version?

**Comment by huyngvu** [comment]
I'm using 9.3

Do I need to upgrade to 9.4 right?

**Comment by sushant12** [comment]
yes you do. the readme has clearly stated the postgres version

**Comment by devton** [comment]
@huyngvu this is because FILTER is only 9.4+
