### ISSUE TITLE
Integrating payment system

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2508]
Can you guys suggest me a way to integrate payment portal like stripe, payapal into catarse?

**Comment by devton** [comment]
hello @sushant12 you can follow the model from github.com/catarse/catarse_pagarme this engine integrate the pagar.me gateway.
I have this old code (https://github.com/devton/catarse_paypal_express) that integrate with paypal but is not updated a log time :(

**Comment by sushant12** [comment]
Thanks @devton
