### ISSUE TITLE
Heroku and postgrest

### ISSUE THREAD

**Issue by nadirali91** [catarse/catarse#2511]
While trying to update the CatarseSettings[:api_host] to my desired postgrest server (which works properly) using "heroku run rails console", nothing gets saved in the database.
I also tried removing the whole database, modified the seed file (adding api_host) and run rake migrate and seed, everything goes well, but nothing gets saved.
Also, I translated all the country names on their specific .rb file (from portuguese to french), when I run rake migrate, I only get the portuguese list of the countries.

**Comment by sushant12** [comment]
Hi @nadirali91 , can you please tell me what you mean by nothing gets saved?

**Comment by nadirali91** [comment]
I modified CatarseSettings[:api_host] to my desired postgrest server.
When I do "heroku restart", and "heroku run rails console" and input CatarseSettings[:api_host] again, the result is "localhost:3004" (and not the one I already put)

**Comment by nadirali91** [comment]
I modified the api_host setting manually.
I deleted the cache, I added api_host to seed.rb and run seed for a new Database (RDS).
I'm deploying to heroku, and I am using my RDS database for that (Not Heroku postgres).
Is there a gem responsible for this ?!
(CatarseSettings[:api_host] still gives localhost:3004)

**Comment by devton** [comment]
weird @nadirali91 the gem is: https://github.com/catarse/catarse_settings_db/

try accessing direct via console using:

```
api_host = CatarseSettingsDb::Setting.find_by_name 'api_host'
api_host.value = 'new_host'
api_host.save
```
