### ISSUE TITLE
What is `sendgrid_mkt_api_key` and `sendgrid_newsletter_list_id` ?

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2512]
I have saved the value for sendgrid port, username and password in the settings table. I am not sure what I should be adding for  `sendgrid_mkt_api_key` and `sendgrid_newsletter_list_id` and where to look for them in sendgrid.

**Comment by devton** [comment]
sendgrid_mkt_api_key -> is for use sendgrid email marketing
sendgrid_newsletter_list_id -> is the list id for subscribe on newsletter list
We use sendgrid marketing campaigns ;) @sushant12

**Comment by sushant12** [comment]
Hi @devton ,

I am still not getting it. 
![screenshot from 2017-03-08 17-52-47](https://cloud.githubusercontent.com/assets/8981250/23703440/13abfcf2-0428-11e7-8bcc-31f58e8da0d4.png)

Where can I find the api key for sendgrid email marketing? and where can i find list id ?

**Comment by sushant12** [comment]
Hi @devton , anything on this one?

**Comment by devton** [comment]
The api key you just generate a new one on -> https://app.sendgrid.com/settings/api_keys
The list id is is the id on url for some contact list here -> https://sendgrid.com/marketing_campaigns/contacts

**Comment by sushant12** [comment]
Thank @devton, you are awesome.
