### ISSUE TITLE
difficulty making sense of brazilian: MoIP vs Pagar.me

### ISSUE THREAD

**Issue by mikesmayer** [catarse/catarse#2522]
I think both of these terms used through out the Catarse code refer to companies that provide payment gateways?

MoIP is https://moip.com.br/en/

Pagarme is https://pagar.me/

These seem to be competing products -- or is one of these words (MoIP) a term to describe a payment gateway?

I noticed in the pagarme gem you describe:

```
mount CatarsePagarme::Engine => "/", :as => "catarse_moip"
```

is that because moip is a technical term?

**Comment by devton** [comment]
@mikesmayer yes MoIP is one gateway and Pagarme is another. on code the correct is
``` 
mount CatarsePagarme::Engine => "/", :as => "catarse_pagarme"
```

**Comment by mikesmayer** [comment]
thanks very much @devton 

i'm wondering if I can ask for some guidance from you and the catarse team on how to ready catarse to use a different payment engine.

you have all done an amazing job and we want to capitalize on all that you're doing. my review of the code I believe there might be a few areas remaining where we could help you complete the modularization of the payment engine design.

i am in the USA and working with @sushant12 is in Nepal -- we didn't know each other before, but we both want to use catarse for different projects, but don't want to take the code in a divergent path from your efforts.

i'm going to email you at your ..tony@gmail.com email address, or you could reach me at mayer@citizensupported.org

thanks!
