### ISSUE TITLE
Error: Sprockets::FileNotFound

### ISSUE THREAD

**Issue by drakhshaniaram** [catarse/catarse#2523]
Hi guys.
Howś it going?

While Iḿ trying to run my catarse project(after doing all the steps in readme file), this error stops me and the project to show up.
FYI: Iḿ using the bitnami package.
![screen](https://cloud.githubusercontent.com/assets/5384436/23772678/c213fc56-04d0-11e7-8261-d9de8172d27a.png)
![screenshot from 2017-03-09 13 40 37](https://cloud.githubusercontent.com/assets/5384436/23772679/c22625e8-04d0-11e7-9b42-3c0371cd432b.png)

couldn't find file 'mithril/mithril.js' with type 'application/javascript'
Checked in these paths: 
  /home/myname/Desktop/catarse/app/assets/images
  /home/myname/Desktop/catarse/app/assets/javascripts
  /home/myname/Desktop/catarse/app/assets/stylesheets
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/jasmine-rails-0.14.1/lib/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/jasmine-rails-0.14.1/lib/assets/stylesheets
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/bundler/gems/redactor-rails-4bd0eadf2f4e/vendor/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/bundler/gems/redactor-rails-4bd0eadf2f4e/vendor/assets/stylesheets
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/cocoon-1.2.9/app/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/catarse_pagarme-2.10.6/app/assets/images
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/catarse_pagarme-2.10.6/app/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/i18n-js-3.0.0.rc15/app/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/dbhero-1.1.12/app/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/dbhero-1.1.12/app/assets/stylesheets
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/bundler/gems/best_in_place-ee95961e6390/lib/assets/javascripts
  /home/myname/rubystack-2.3.3-1/ruby/lib/ruby/gems/2.3.0/gems/jasmine-core-2.5.2/lib/jasmine-core
  /home/myname/Desktop/catarse/spec/javascripts

----------------------------

_app_views_catarse_bootstrap_projects_index_html_slim__316837007403687657_70138352556380
app/views/catarse_bootstrap/projects/index.html.slim
1 2 3 4 5 6 7 8 9 10 11

- content_for :title, t('site.title')

/ = render 'shared/header_big', overlayer: true

#application[data-currentuserid=current_user.try(:id) data-hasfb="#{current_user.try(:has_fb_auth?)}"]

  .w-section.hero-full.hero-full-slide

= javascript_include_tag 'api/application'

/ section#blog.section-large.bg-gray.before-footer

/   .w-container

/     .u-text-center

/       = link_to CatarseSettings[:blog_url], target: :blank do

/         = image_tag "icon-blog.png", class:
 "u-marginbottom-10"

**Comment by sushant12** [comment]
have u run bower install inside your project directory?

**Comment by drakhshaniaram** [comment]
Hi @sushant12 
Yes.
let me have a look again.

**Comment by drakhshaniaram** [comment]
Yes I have ran it. But itś the same. I got that error again.

**Comment by monaka** [comment]
Same here. I got this issue on building with docker-compose.

Just guess but it should be `mithril` instead of `mithril/mithril.js`?
I found `//= require mithril` in `app/assets/javascript/application.js`.
