### ISSUE TITLE
Decouple bank account and user address from the project publish process

### ISSUE THREAD

**Issue by mikesmayer** [catarse/catarse#2524]
First let me say, you're all doing amazing work and I'm really grateful for all that you've done with the catarse project.

That said, I have a request for improving the project creation process.

Both to remove friction for end users and for third party developers like myself working to port Catarse to our local geographies, it would be great to decouple the bank_account and user address  elements in the basic project publishing process.

I realize that the base_validator.rb, user.rb and related validations, etc are all much in active development -- but since I don't know the roadmap, I can only speak to the pain I'm experiencing right now.

The issues I have are two fold:

1) Requiring all this information from a project creator is poor from a usability perspective. It would boost acquisition and activation around the supply of project creators by limiting the inputs they need to complete to get a project listed.

Generally, fewer inputs are way better.

None of the major crowdfunding platforms require bank account, cpf or complete address information in the initial project creation process. It would be better to require that information within a shortened time period of launching the project.

Kickstarter requires people to declare the country of legal residence which probably meets the basic legal compliance concerns of running a crowdfunding platform.

I realize controls and compliance are real concerns -- I'm not suggesting shelving the validation, just pushing it back in the user's lifecycle.

2) For those of us eager to contribute to your amazing work and bring this great project all around the world -- the current project create/publish process is a bit of a pain. 

In its current design, to create and publish a project, user touches the project model, user model, bank_account model PLUS a handful of models related to the payment engine.

This is causing significant heartburn as I'm working on an engine to stripe_connect: https://stripe.com/connect which solves some of the controls and compliance issues around running a marketplace like this...

So because the current architecture is difficult to extend, it makes it hard for outside developers to contribute to the project.

I recognize that you're very much actively developing several of the pieces of code that my issues here touch so its difficult to propose some possible paths to refactoring and decoupling these functions. So to the degree that they could be incorporated into where you're going, that would be excellent.

Thanks!

**Comment by devton** [comment]
Hey @mikesmayer thanks a lot for your feedback and sorry about the delay to answer here.

We are working to decouple these informations from publishing process in these next weeks,
The first step was unifying user and project_accounts information that has duplicated info (address, bank_data).

The next is to implement some background doc check (thirdparty) for reduce only to legal user data only(name, document) and move bank_account validation to a balance/withdraw flow in user dashboard.

We are planning to use github projects to put our major releases changes.

**Comment by sushant12** [comment]
that is awesome news @devton

**Comment by luisofribeiro** [comment]
@mikesmayer @sushant12 

We've just started to put issues and PR a github's project called ROADMAP: https://github.com/catarse/catarse/projects/2

Feedbacks are welcome.

**Comment by mikesmayer** [comment]
excellent -- i'm excited to help out. just left an initial comment, but will dig into those 3rd party services now.

**Comment by luisofribeiro** [comment]
I'm closing this issue. We are decoupling bank account from projects and develiping a user balance here: https://github.com/catarse/catarse/pull/2596

**Comment by sushant12** [comment]
Thanks @luisofribeiro

**Comment by mikesmayer** [comment]
thanks! @luisofribeiro
