### ISSUE TITLE
 materialized view is not populated

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2532]
I cant see contribution graph in the project dashboard? I have seed the db with some campaign and contribution data with payment state paid but the project dashoard is not showing any chart. I ran the rake task `rake cron:refresh_materialized_views ` but got an err like this

```
ActiveRecord::StatementInvalid: PG::FeatureNotSupported: ERROR:  CONCURRENTLY cannot be used when the materialized view is not populated
: REFRESH MATERIALIZED VIEW CONCURRENTLY "1".statistics
```

It would be great if you could tell me how and when the data in materialized view is populated

**Comment by devton** [comment]
hello @sushant12 for this materialized views you should run the refresh materialized view without concurrently when is first time ;)

**Comment by sushant12** [comment]
Thanks @devton
