### ISSUE TITLE
Cannot read property 'toggleClass' of undefined

### ISSUE THREAD

**Issue by kozeyandrey** [catarse/catarse#2535]
Hello guys,
when I had touched to the my account's dropdown at a page's header, I got this js errors in the browser console:

> Uncaught TypeError: Cannot read property 'toggleClass' of undefined
>     at n.toggleMenu (application-0017332….js:13)
>     at HTMLHtmlElement.dispatch (application-0017332….js:2)
>     at HTMLHtmlElement.g.handle (application-0017332….js:2)

Please, help. Thanks!

Regards, Andrew.

**Comment by bonafernando** [comment]
I'm experiencing the same... Works fine on development, but it's not working on Heroku. Anyone know how to solve it? (tag v2.0)

**Comment by vicnicius** [comment]
@bonafernando it's a bit hard to tell. It could be due to bower deprecation but I am really just guessing here. You could try to run it on heroku in development mode and then try to debug it.

**Comment by bonafernando** [comment]
@vicnicius , thanks for the quick answer...

Besides this error, I also receive two other error that might be a clue to what's happening...

You can see inspecting the page on: https://serene-island-40633.herokuapp.com

I'm almost sure it's something I configured wrong....

**Comment by vicnicius** [comment]
there I can see:

`Uncaught TypeError: mixpanel.track is not a function` is probably related to not having mixpanel configured properly and the other one `Uncaught SyntaxError: Unexpected token ;` is related to not having [vwo](https://vwo.com) properly setup. You can either set them correctly on your Settings DB (you can do this from rails console using CatarseSettings) table or remove the services. Fixing this should fix the problem mentioned on the issue.

**Comment by bonafernando** [comment]
How could I remove those services?

**Comment by bonafernando** [comment]
@vicnicius 
I can see why you didn't see the other error mentioned before. It happens only when clicking on your profile picture when logged in.

But here is what happens:

```
Uncaught TypeError: Cannot read property 'toggleClass' of undefined
    at n.toggleMenu (application-6d09d9054655a85d907f8668408feee0.js:13)
    at HTMLHtmlElement.dispatch (application-6d09d9054655a85d907f8668408feee0.js:2)
    at HTMLHtmlElement.g.handle (application-6d09d9054655a85d907f8668408feee0.js:2)
```

**Comment by vicnicius** [comment]
You can just try to look for the places where those services' JS are included and remove it. They are probably on a template partial somewhere. And it's probably because of the fact that they are breaking that the rest of the js is also. But as I said, I'm not entirely sure. It's been a while since we released v.2.0.

**Comment by bonafernando** [comment]
@vicnicius thank you very much! After removing the dependencies everything worked fine!
