### ISSUE TITLE
CatarseSettings['vwo_id'], CatarseSettings['hotjar_id']

### ISSUE THREAD

**Issue by kozeyandrey** [catarse/catarse#2542]
Hello guys,

Could you please say me, for what do i need to use CatarseSettings['vwo_id'], CatarseSettings['hotjar_id'] properties?

Thanks!

Regards,
Andrew

**Comment by vicnicius** [comment]
You don't need to use it. It was used for integration with https://vwo.com/.

Em seg, 20 de mar de 2017 às 13:58, Andrew Kozey <notifications@github.com>
escreveu:

**Comment by kozeyandrey** [comment]
Thanks! What about hotjar? Don't i need to use it too?

**Comment by vicnicius** [comment]
Not really. Also a third-party service.

Em seg, 20 de mar de 2017 às 14:32, Andrew Kozey <notifications@github.com>
escreveu:

**Comment by kozeyandrey** [comment]
@vicnicius Got it. Thanks
