### ISSUE TITLE
Payments process in Ukraine.

### ISSUE THREAD

**Issue by kozeyandrey** [catarse/catarse#2548]
Hello guys,

Could you please help me understand what Payment System I should use for payments process in Ukraine and will suit me a system for doing this in Catarse which contains by default?

Thanks!

Regards,
Andrew.

**Comment by devton** [comment]
hello @kozeyandrey currently our payments is processed using pagar.me (like a stripe in BR). you can take a look on github.com/catarse/catarse_pagarme to see the workflow of payment processor and create one to integrate with some custom payment engine on Ukraine.


[]'s
