### ISSUE TITLE
Create user with the admin permissions

### ISSUE THREAD

**Issue by kozeyandrey** [catarse/catarse#2552]
Hello guys,

Could you please help me understand how i can create a user with the admin permissions?

Thanks!

Regards,
Andrew.

**Comment by adrianob** [comment]
You have to create it using the rails console(or directly on the db). Just set admin=true on the user model.

**Comment by kozeyandrey** [comment]
This parameter is protected
I've got this error, during updating a user (User.first.update(admin: true))
WARNING: Can't mass-assign protected attributes for User: admin

**Comment by adrianob** [comment]
You can update it like this:
```User.first.update_attribute :admin, true```

**Comment by kozeyandrey** [comment]
Got it. Thanks.
