### ISSUE TITLE
Header text are not coming from .yml

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2598]
I noticed that the header link text is set in the .js file and is not coming from the yml.

It's coming from catarse.js:

    }, [m('.w-row', [m('.w-clearfix.w-col.w-col-8.w-col-small-8.w-col-tiny-8', [m('a.header-logo.w-inline-block[href=\'/?ref=ctrse_header\'][title=\'Catarse\']', ctrl.homeAttrs(), m('img[alt=\'Logo big\'][src=\'/assets/catarse_bootstrap/logo_big.png\']')), args.menuShort ? '' : m('div#menu-components', [m('a.w-hidden-small.w-hidden-tiny.header-link.w-nav-link[href=\'/start?ref=ctrse_header\']', { config: m.route }, 'Comece seu projeto 2'),

**Comment by sushant12** [comment]
@ACPK do u mean translation text?

**Comment by ACPK** [comment]
@sushant12 - I mean the text in header. My app is showing the hardcoded text rather than the transaction text.

**Comment by sushant12** [comment]
translations are not yet implement all over the app

**Comment by ACPK** [comment]
@sushant12 - Why are they included in the YML then, which made it seem like it should be at first glance?

**Comment by ACPK** [comment]
@sushant12  - It reads from the YML on Heroku but not locally.
