### ISSUE TITLE
Unable to start API server

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2599]
When I run:

     ./postgrest postgres://postgrest@localhost/catarse_development -a anonymous --jwt-secret gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr9C -s 1 -p 3004

I get: 

   zsh: no such file or directory: ./postgrest

Postgrest was installed via Homebrew and can be found within /usr/local.

When I changed the path it's reading Postgrest from, I get:

    Invalid option `-a'

**Comment by scanferla** [comment]
This also happens to me!

**Comment by jcserracampos** [comment]
PostgREST after v4 expects a configuration file so you can't use -a or --jwt-secret.
Download v 0.3.x or create a config.
