### ISSUE TITLE
Unable to bunde: JWT fatal: Needed a single revision

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2600]
When I run rake db:migrate for the first time, I get:

    /Users/andrewkelley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json_web_token-0.2.2/lib/json_web_token.rb:35: warning: already initialized constant JWT
    /Users/andrewkelley/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt-1.5.6/lib/jwt/json.rb:4:             
    warning: previous definition of JWT was here
    fatal: Needed a single revision

**Comment by ACPK** [comment]
Related to: https://github.com/catarse/catarse/issues/1862

**Comment by sushant12** [comment]
what version of postgrest are you using? what is your postgres sql version?

**Comment by ACPK** [comment]
I'm using 9.6 (9.4 has security issues) and here's my code:   https://github.com/ACPK/start

**Comment by sushant12** [comment]
i tired using the latest postgrest version and got errs so i had to fall back to 0.3

**Comment by ACPK** [comment]
@sushant12 - Did you try to solve it? Looking to solve it now.

**Comment by sushant12** [comment]
@ACPK no I did not. I am focused in getting the platform up and running  and getting some visitors for now

**Comment by ACPK** [comment]
@sushant12 - I was an error on my part as I got the name of the second schema incorrect. We were successfully able to update the site to the latest version of Postgres and Rails, and are in the process of adding stripe today.
