### ISSUE TITLE
Unable to load API

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2603]
When a non-logged in user goes to localhost:3000/start, no categories show up in the dropdown menu. Please note that there are categories in the database.

**Comment by sushant12** [comment]
looks like your app is not able to communicate with postgrest server. refresh that page again and check your postgrest server and see if it will log somethignin the console

**Comment by ACPK** [comment]
@sushant12 - That's correct. I noticed in the logs that it's hitting a 401.

**Comment by sushant12** [comment]
i am assuming that it has something to do with the postgrest version or the api token and api host

**Comment by ACPK** [comment]
@sushant12  - Nope, it had to do with the schema name. I didn't realize that Catarse creates a schema named "1".

**Comment by WizardKid** [comment]
can someone elaborate on this as I point the api to schema "1" and it crashes but it doesn't crash when I point it to public
