### ISSUE TITLE
"Busque projetos" is hardcoded in catarse.js

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2610]

**Comment by sushant12** [comment]
@ACPK yes. But you can change them if you [compile the lib](https://github.com/catarse/catarse.js) yourself . I have done some translations changes in [my forked repo](https://github.com/sushant12/jvn)

**Comment by ACPK** [comment]
@sushant12 - Thoughts on not using catarse.js's header components and having it be within the same repo? I would think it's a pain to also have to manage sushant12/catarse.js. Alternative the source code for catarse.js, which is what I've done for a number of gems.

**Comment by vicnicius** [comment]
@ACPK @sushant12 not using catarse.js's header should be pretty straightforward. Just removing [this line](https://github.com/catarse/catarse/blob/master/app/assets/javascripts/api/application.js#L101) and adding [this](https://github.com/catarse/catarse/blob/master/app/views/catarse_bootstrap/shared/_header.html.slim) to your template should do the work.

**Comment by ACPK** [comment]
@vicnicius - What would be the downside? For example, it'll show up on pages where Catarse.js's header is excluded (ex: login and signup).

**Comment by vicnicius** [comment]
The pages where catarse.js is excluded do not use catarse.js's header. The one's you mention are implemented on top of devises templates. The main downside is not being able to communicate with the components rendered by catarse.js from the header component. Client-side routing from the menu, for example, wouldn't be possible, or at least would have to be implemented on a hacky way. And I'm not sure if something would break on the search component. If you are looking for a monolithic approach, you could take a look at our [last monolithic release](https://github.com/catarse/catarse/releases/tag/v2.0).
