### ISSUE TITLE
Password reset token expires before the time specified in config.reset_password_within

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2612]

**Comment by sushant12** [comment]
If i try to reset password with url `/pt/password/new` then i can reset the password but when the url is `/en/password/new` then i get token expire issue.

**Comment by sushant12** [comment]
I am unable to think of any reason why this could be happening.

**Comment by sushant12** [comment]
@vicnicius can u think of any reason?

**Comment by vicnicius** [comment]
Hmmm...this is really weird. I'll try to investigate it later this week.

**Comment by sushant12** [comment]
@vicnicius sure , thanks mate

**Comment by sushant12** [comment]
@vicnicius hey man, anything on this one?

**Comment by vicnicius** [comment]
Hi @sushant12. I did some investigation on this but couldn't move further. Is the locale value of the user record you are trying to reset also set to 'en'?

**Comment by sushant12** [comment]
@vicnicius i tested with user`s locale value set to en in db but I am still getting the error

**Comment by vicnicius** [comment]
@sushant12 hmm. maybe the team at https://github.com/plataformatec/devise could help us with some insights?

**Comment by sushant12** [comment]
there is something wrong when the token is being generated with en in the url.

First I used this url http://localhost:3000/pt/password/new to send the passowrd reset email then in this url http://localhost:3000/pt/password/edit?reset_password_token=vxKmFG49DyRrVCbnXonA I changed the pt to en and it changed the password successfully. 

I guess there is something wrong when generating the token while the url has en

**Comment by sushant12** [comment]
https://github.com/plataformatec/devise/issues/2615

that solved it

**Comment by vicnicius** [comment]
Thank you very much for your PR, @sushant12!
