### ISSUE TITLE
PostgreSQL 9.5 on RDS: permission denied to set role \"anonymous\

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2615]
I'm using PostgreSQL 9.5 as the version was specified in the Docker Compose. The migration seems to have run but I get the error below.

    permission denied to set role \"anonymous\

**Comment by vicnicius** [comment]
@ACPK please take a look at https://gitter.im/begriffs/postgrest/archives/2015/09/29 and see if it helps.

**Comment by ACPK** [comment]
@vicnicius -  No luck.

NOTICE:  role "staging" is already a member of role "anonymous"
NOTICE:  role "staging" is already a member of role "anonymous"
GRANT

Query returned successfully in 255 msec.
