### ISSUE TITLE
Failed to execute "git ls-remote --tags --heads https://github.com/lhorie/mithril.git"

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2621]

**Comment by ACPK** [comment]
The repo url has changed.

**Comment by sushant12** [comment]
In bower.json of catarse update value of mithrill to  "mithril": "https://github.com/MithrilJS/mithril.js.git#0.2.4" . You can send a PR too

**Comment by vicnicius** [comment]
yeah.. they re-structured mithril's repo and we missed some updates.

**Comment by ACPK** [comment]
@sushant12 - Where is the value mithrill? I only see mithril.

**Comment by sushant12** [comment]
@ACPK , sorry for the typo. it is mithril. Did it work?

**Comment by ACPK** [comment]
@sushant12  - Replacing the word mithril with the word mithril isn't a change. However, I did change the repo URL in Catarse and Catarse.js to no avail.

**Comment by sushant12** [comment]
@ACPK mithril-postgrest also use the mithril lib . I had to clone the mithril-postgrest lib and make changes there , then create a new bower package and include it in my bower.json file. So instead of mithril-postgrest, I am using my mithril-grasruts-postgrest

**Comment by sushant12** [comment]
@ACPK , have u run bower install by first removing the everything inside vendor/assets/components dir and then running bower cache clean.

**Comment by ACPK** [comment]
@sushant12 @vicnicius  - I did a clean install (new app downloaded from catarse about an hour ago), and I still get this error if I run "Bower Update".

**Comment by ACPK** [comment]
@sushant12 - Tried to with a brand new clone.
