### ISSUE TITLE
catarse deployment on centos 7

### ISSUE THREAD

**Issue by premkanish** [catarse/catarse#2626]
@sushant12  @devton please help me with guided steps for the catarse deployment of english language on centos as i am confuse.

**Comment by sushant12** [comment]
Catarse was built with Paas on mind but I am deploying catarse in my ec2  ubuntu instance.

I am using capistrano to deploy. I have puma as my application server.

**Comment by premkanish** [comment]
@sushant12  can you please share the details and which files to edit.

Thanks!

**Comment by sushant12** [comment]
@premkanish [this](https://www.sitepoint.com/deploy-your-rails-app-to-aws/) is a good tutorial.

**Comment by premkanish** [comment]
@sushant12 ok got it. This part is done but which files i have to change in catarse folder to make it ready for the production

**Comment by sushant12** [comment]
@premkanish it will be all taken care of by capistrano. The only problem that I am facing right now is memory bloating issue. Sidekiq some how consumes RAM gradually and then plateaus
