### ISSUE TITLE
memory leak or memory bloat

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2627]
I know that you guys made Catarse with Paas in mind but I deployed my app to aws. RAM usuage for Catarse increase gradually if I visit the project view page.

I may be wrong because it is hard to debug. Sometimes the memory will gradually rise and plateau.

**Comment by devton** [comment]
@sushant12 what specs from server?

**Comment by sushant12** [comment]
@devton I ma running t2 micro ec2 ubuntu server.
![screenshot from 2017-05-19 19-17-16](https://cloud.githubusercontent.com/assets/8981250/26249850/ccf73668-3cc7-11e7-9868-067e81045bd3.png)

**Comment by sushant12** [comment]
This is my puma config

```
#!/usr/bin/env puma
 
directory '/home/deploy/jvn/current'
rackup "/home/deploy/jvn/current/config.ru"
environment 'production'
 
pidfile "/home/deploy/jvn/shared/tmp/pids/puma.pid"
state_path "/home/deploy/jvn/shared/tmp/pids/puma.state"
stdout_redirect '/home/deploy/jvn/shared/log/puma_error.log', '/home/deploy/jvn/shared/log/puma_access.log', true
 
 
threads 0,8
 
 
 
bind 'unix:///home/deploy/jvn/shared/tmp/sockets/puma.sock'
 
workers 0
 
 
 
 
 
prune_bundler
 
 
on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/deploy/jvn/current/Gemfile"
end
```

**Comment by sushant12** [comment]
this is the result from scoutapp
![screenshot from 2017-05-19 19-43-41](https://cloud.githubusercontent.com/assets/8981250/26250981/84860874-3ccb-11e7-8d47-b5808c9cc1a9.png)
