### ISSUE TITLE
error when rake db:create

### ISSUE THREAD

**Issue by premkanish** [catarse/catarse#2628]
@sushant12  @devton 

DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <top (required)> at /home/zimba/catarse/config/application.rb:7)
/home/zimba/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json_web_token-0.3.2/lib/json_web_token.rb:36: warning: already initialized constant JWT
/home/zimba/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jwt-1.5.6/lib/jwt/json.rb:4: warning: previous definition of JWT was here

**Comment by sushant12** [comment]
Those warnings are ok to ignore. Is not your app running?

**Comment by premkanish** [comment]
(called from <top (required)> at /home/zimba/catarse/config/application.rb:7)

It is running but i want to understand the above line.
