### ISSUE TITLE
ContributionDetailDecorator test fail

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2631]
Based on the tests below that fail, the ContributionDetailDecorator is removing the removing the decimal places.

    describe "#display_value" do
      subject{ detail.decorate.display_value }

      context "when the value has decimal places" do
        let(:value){ 99.99 }
        it{ is_expected.to eq("R$ 99,99") }
      end

      context "when the value does not have decimal places" do
        it{ is_expected.to eq("R$ 10,00") }
      end

**Comment by vicnicius** [comment]
@ACPK tests for `"#display_value"` are green and though I think we do not use those decorators on production anymore, they seemed to be working just fine. We do have some tests the occasionally might fail because of date time issues, but those are the `#display_date` method tests.
