### ISSUE TITLE
Payment to India

### ISSUE THREAD

**Issue by ramandhingra** [catarse/catarse#2632]
Hi

I have very little knowledge about payments engines/gateways. I live in INdia and I need that the money generated from the the Catarse platform should be transferred to my Indian bank account. What do I need to do to accomplish this?

Thanks in advance
Raman

**Comment by vicnicius** [comment]
Hi, @ramandhingra. To accomplish this you have to make an integration with a payment provider that works with Indian banks. It looks like https://www.payubiz.in/ is one example. Basically what you want is a service that is able to process customer's payments, give you the possibility to transfer the money from the processed payment to your (usually your company's) account and that provides a way of showing you the status of those payments, so you can sync with the platform. This is usually what a payment gateway or payment provider offers you. To accomplish this in Brazil we use https://pagar.me, and the integration can be seen here: https://github.com/catarse/catarse_pagarme. This gem is a good way to understand how this process works from the platform perspective.
