### ISSUE TITLE
Is there an overview of the system?

### ISSUE THREAD

**Issue by hungryzi** [catarse/catarse#2651]
We're trying to set up an 1-project website for crowdfunding and I'm evaluating if Catarse is too complex for this.

I did setup a local version and played around but I stumbled into many problems due to the fact that I want to use it in English & without Pagarme. Thus I'm trying to do this from the code instead.

Usually I would go to `schema.rb` to try to understand the relationships between objects and the scope of projects. However, running `rake db:schema:dump` fails with `TSort::Cyclic: topological sort failed`. And the pg_dump output is pretty hard to read. Is there another way for me to get the overview of the system, including its user-facing and admin-facing features?

**Comment by vicnicius** [comment]
@hungryzi you can have a good data-level overview of catarse with [pgadmin](https://www.pgadmin.org/). The issues with both, translations and payment integration, are things we are aware of and working to fix, but it will still take us some time. There are other developers (here on our issues even) that made progress on this, so maybe they could help you by pointing out the issues they faced. 

If you wish, we also have [the latest release](https://github.com/catarse/catarse/releases/tag/v2.0) with a monolithic rails version of the platform, which could make it easier to understand and iterate on the code, but will demand some work on updating things. 

We would appreciate hearing about other issues you will possibly face. We really want to improve a lot on the developer experience of using our platform, and we will be able to do this way better with great feedback from the devs out there willing to try the platform and help us.

**Comment by hungryzi** [comment]
Thanks @vicnicius for the suggestion.

I think Catarse is not suitable for my current project, but i'm interested in helping with localization. I will be following https://github.com/catarse/catarse/issues/2639.
