### ISSUE TITLE
Next PostgREST and API Gateway versions?

### ISSUE THREAD

**Issue by ppKrauss** [catarse/catarse#2652]
Hi, it is ok to post a suggestion and/or invitation here?

The suggestion is to express Catarse APIs by OpenApi (so using Swagger)... And enhance the use of  PostgREST, by [PostgREST-writeAPI](https://github.com/ppKrauss/PostgREST-writeAPI).

I am working at Sampa-SP-Brazil (!)... Somebody here want to help me with this little project at Swagger-codegen? See https://github.com/swagger-api/swagger-codegen/issues/5034#issuecomment-306267653

**Comment by vicnicius** [comment]
Thanks for the suggestion, @ppKrauss. We will take a look at the project, for sure.
