### ISSUE TITLE
QUESTION: Caching Projects

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2653]
I saw that fragment caching is used for projects. Is the data for projects#show called directly via the database or via PostgreSQL?

**Comment by vicnicius** [comment]
I am not sure if I am answering your question, but the data used in projects today is fetched from rails (active records querying our postgres database) and also some complimentary data is fetched via our api (postgrest querying our postgres database).

**Comment by ACPK** [comment]
@vicnicius - An example would be caching the categories which come directly from PostgREST.

**Comment by vicnicius** [comment]
@ACPK PostgREST relies on the database own performance capabilities. Postgres already does a lot of query optimizations on it's own, but there are specific techniques you could use to have more control and even better performance on your endpoints. In our project we make use of materialized views to query rarely updated data sources (project categories would be one of those cases) but you could probably also use `PREPARE` and queries inside PL/plSQL functions.
