### ISSUE TITLE
is there any point in using this code ?

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2668]
Is this piece of  [code](https://github.com/catarse/catarse/blob/develop/app/controllers/projects/contributions_controller.rb#L40-L45) used anymore? Correct me if i am wrong, the reward showing part is also handle by the js and not by the ruby code.

**Comment by vicnicius** [comment]
You are completely right, @sushant12. Willing to make a PR to remove it?

**Comment by ACPK** [comment]
@sushant12  - +1 to the PR :) Thank you!

**Comment by sushant12** [comment]
@vicnicius  ya sure i can do that

**Comment by blaiser49** [comment]
#2783 Fixed?
