### ISSUE TITLE
Error setting project owner

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2678]
When I created a project via the console (manually), the user that shows up when I visit "/projects/2/edit#user_settings" is not the one whose id is attributed to the project user_id.

What is the correct way to manually set the project owner?

**Comment by adrianob** [comment]
That should work. Which id is being passed to the user_details endpoint?

**Comment by ACPK** [comment]
@adrianob - I fixed the issue, but found that the sidebar shows up for admins but not for the project owner. If I may ask, where should I look to resolve this issue?

**Comment by adrianob** [comment]
Did you create the web_user role in the db before running migrations? The sidebar will show up if the call to ```is_owner_or_admin``` on the db returns true, try to console.log() the object that is calling this function to see what's going on.

**Comment by ACPK** [comment]
@adrianob - Yes, I had created the role.

I can view the sidebar if I manually visit: http://localhost:3000/projects/4/edit#preview

**Comment by ACPK** [comment]
@adrianob - Any thoughts. It seems to be caused by a callback to "http://localhost:3000/projects/undefined".

**Comment by ACPK** [comment]
@adrianob - Could it be due to a callback to "Started GET "/en/users/1/null"" which is returning a 404 status?

**Comment by adrianob** [comment]
@ACPK that's definitely related. The API is not returning the correct user_details for some reason, try to query the db directly on "1".user_details (after setting appropriate user) and see what's being returned. Also, check the browser console for any request errors, there should be an error message on the user_details endpoint.

**Comment by ACPK** [comment]
@adrianob - I checked the console and there's no errors for user_details. The columns come back null which must be related to is_owner_or_admin.
