### ISSUE TITLE
Refreshing States

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2684]
How do I refresh the "states" MATERIALIZED view after adding a new one via the console?

ex: http://api.catarse.me/states

**Comment by ACPK** [comment]
I got it working with pgAdmin but I'm assuming this sound be included in the Wiki.

**Comment by sushant12** [comment]
did u refresh it with the rake taasks?

**Comment by ACPK** [comment]
I didn't see the rake task for this though I saw it for other materialized views.
