### ISSUE TITLE
User email with PostgreSQL is null

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2692]
The user's name is showing up but the email is null.

**Comment by ACPK** [comment]
Could it be due to "Started GET "/en/users/1/null" which is returning a 404 status?

**Comment by adrianob** [comment]
@ACPK we had a bug with the latest version of postgrest and non-admin users, please check again with the latest commit on develop branch.

**Comment by ACPK** [comment]
@adrianob - Thank you for letting me know, as we appreciate it. I went through the develop branch, but didn't see which commit directly addressed the issue. Would you mind sharing?

On another note, does this fix also address https://github.com/catarse/catarse/issues/2678?

**Comment by adrianob** [comment]
https://github.com/catarse/catarse/commit/8739c15d3a755cb535bba2dfc926af41b3ec9bf5

It might be related to the other issue if you were testing with non-admin users.

**Comment by ACPK** [comment]
@adrianob -  I ran that migration but it broke the project edit page which was working beforehand.  I now get the errors below.

    SQL (16.1ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "A frase de efeito do projeto não pode ficar em branco"], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.308182"], ["updated_at", "2017-07-21 19:16:22.308182"]]
    SQL (16.1ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "Portfolio image cannot be empty"], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.330715"], ["updated_at", "2017-07-21 19:16:22.330715"]]
    SQL (16.0ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "Zip code cannot be blank."], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.349193"], ["updated_at", "2017-07-21 19:16:22.349193"]]
    SQL (16.3ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "State cannot be blank."], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.366902"], ["updated_at", "2017-07-21 19:16:22.366902"]]
    SQL (16.1ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "Country cannot be blank"], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.384829"], ["updated_at", "2017-07-21 19:16:22.384829"]]
    SQL (16.2ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "City can not be left blank."], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.403398"], ["updated_at", "2017-07-21 19:16:22.403398"]]
    SQL (16.2ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "Address can not be empty."], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.421869"], ["updated_at", "2017-07-21 19:16:22.421869"]]
    SQL (16.2ms)  INSERT INTO "project_errors" ("error", "to_state", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["error", "O valor da meta não pode ficar em branco"], ["to_state", "online"], ["project_id", 7], ["created_at", "2017-07-21 19:16:22.439812"], ["updated_at", "2017-07-21 19:16:22.439812"]]
     (16.0ms)  ROLLBACK
    Project Load (16.8ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT 1  [["id", 7]]
    Completed 400 Bad Request in 393ms (Views: 0.1ms | ActiveRecord: 346.9ms)

**Comment by ACPK** [comment]
@adrianob - The call to http://localhost:3000/projects/7/validate_publish comes back as:

    {"errors_json":"{}"}

**Comment by adrianob** [comment]
@ACPK is your repo in synch with the develop branch? I've never seen this happen, if any validation errors occurred they should be returned in this hash. I don't know how to help you here.. try debugging the validate_publish method on the controller and the transition here: https://github.com/catarse/catarse/blob/develop/app/state_machine/flex_project_machine.rb#L33

**Comment by ACPK** [comment]
It still shows this bug locally, but production is fine.
