### ISSUE TITLE
"has_notifications" and "new user welcome email".

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2710]
If I may ask, how does the **has_notifications** feature work and what triggers the "new user welcome email"? I noticed that user notifications are not created upon signup when testing via localhost.

**Comment by adrianob** [comment]
```has_notifications``` comes from the user_notifier gem https://github.com/diogob/user_notifier
The new user notification is created on the after_create callback which is defined on the user_observer.

**Comment by ACPK** [comment]
@adrianob - Thanks
