### ISSUE TITLE
Mixpanel - Not being used?

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2714]
It seems like the code for Mixpanel is not getting called even when i set the mixpanel_token. Is it still being used?

The two calls are no longer in catarse_bootstrap.html.haml

    = render_google_analytics_script
    = render_mixpanel_script

**Comment by vicnicius** [comment]
yeah, we are not using it anymore.

**Comment by ACPK** [comment]
@vicnicius - Awesome thanks. Any recommendations based on what you're using instead?

**Comment by vicnicius** [comment]
yes, we've been using http://www.metabase.com/.
