### ISSUE TITLE
FB Login Error: "Could not authenticate you from Facebook because "Invalid credentials"."

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2716]
I'm hitting an error which may be caused by my Facebook version (v2.9)

    https://stackoverflow.com/questions/16176208/rails-could-not-authenticate-you-from-facebook-because-invalid-credentials

From my logs, I see that the error is:

    error":{"message":"Error validating client secret.","type":"OAuthException","code":1,"fbtrace_id":""}

Has anyone else hit this error?

**Comment by ACPK** [comment]
https://github.com/catarse/catarse/issues/2529

**Comment by sushant12** [comment]
for this i had to clear my tmp dir and restart my app.

**Comment by ACPK** [comment]
@sushant12 - Found out that the secret was actually incorrect. However, I now hit the issue "ActiveRecord::RecordInvalid: Validation failed: Senha Password can not be empty.". Did you get this?

**Comment by sushant12** [comment]
nope not that particular issue but i often do get the invalid creds issue.
