### ISSUE TITLE
Failing Observer Specs (ex: "from_waiting_funds_to_successful" and "UserObserver after_create")

### ISSUE THREAD

**Issue by ACPK** [catarse/catarse#2724]
What calls the spec "from_waiting_funds_to_successful" as the Rspec tests for many of the observers are failing?  I thought it was an issue due to my Stripe integration as I'm creating a Payments Gem, but the New User Observer spec is also failing.

**Comment by ACPK** [comment]
Here's an error that I'm seeing:

    warning: parser/current is loading parser/ruby24, which recognizes
    warning: 2.4.0-compliant syntax, but you are running 2.4.1.
    warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
    Run options: include {:focus=>true, :locations=>{"./spec/observers/user_observer_spec.rb"=>[14]}}

**Comment by adrianob** [comment]
These callbacks are defined dynamically here https://github.com/catarse/catarse/blob/develop/app/state_machine/flex_project_machine.rb#L98

**Comment by adrianob** [comment]
As for the user observer, all callbacks are defined in the usual way. I'm not sure what error you're getting but if you are using the catarse_pargarme gem as the base it might have something to do with the validations performed here: https://github.com/catarse/catarse_pagarme/blob/master/app/models/catarse_pagarme/bank_account_concern.rb

**Comment by ACPK** [comment]
@adrianob - It was partly due to "rails_observer" not being at v1.0 yet. The version I was using did not instantiate on app boot, but the gem maintainer has fixed the bug.  

https://github.com/rails/rails-observers/releases

**Comment by ACPK** [comment]
@adrianob  - Do observers run when data is created via the console? I'd like to be able to upload contributions manually without notifications being sent (i.e.: for migration purposes).

**Comment by adrianob** [comment]
@ACPK they do. You can either create you migrations in sql or use rails methods that do not run callbacks such as ```update_columns```.

**Comment by ACPK** [comment]
@adrianob - So making edits via the console right now will create notifications?

**Comment by adrianob** [comment]
Not every edit will create a notification... Which notification in particular you don't want being created? There are many ways to stop running callbacks, I just gave an example. 
So far this has not been a problem for us in production, we rarely use rails for migrations and when we do it's quite easy to avoid callbacks.

**Comment by ACPK** [comment]
An example would be creating a contribution manually as we're migrating from an existing site.

**Comment by adrianob** [comment]
@ACPK you could just disable the observer all together for your migration, like this for example ``` User.observers.disable :all { User.create! email: 'foo@bar.com', password: '123456'}```

**Comment by ACPK** [comment]
@adrianob  - The UserNotifications are now created for new signups but no welcome email is sent. Sendgrid is correctly configures as the "password reset" email gets sent, but what am I missing?

**Comment by ACPK** [comment]
@adrianob  - The UserNotifications are now created for new signups but no welcome email is sent. Sendgrid is correctly configures as the "password reset" email gets sent, but what am I missing?

**Comment by adrianob** [comment]
@ACPK are you running the listen task?
https://github.com/catarse/catarse/blob/develop/lib/tasks/listen.rake

**Comment by adrianob** [comment]
You also need to run sidekiq for notifications to actually be delivered.
