### ISSUE TITLE
Facebook login not working. What went wrong?

### ISSUE THREAD

**Issue by huabawa** [catarse/catarse#2756]
![screen shot 2017-08-18 at 7 14 54 pm](https://user-images.githubusercontent.com/30085950/29482615-8eb3292e-8449-11e7-8618-1a57408c8fd0.png)
When I click on connect to facebook on the home page, the following appears.

> Sorry, something went wrong.
> 
> We're working on getting this fixed as soon as we can.

What changes do I need to make to enable facebook login? 

Thanks!

**Comment by vicnicius** [comment]
You have to correctly configure your facebook app and add it's id to the facebook_app_id entry on our settings. You can do so by updating the settings table on your database or by running `CatarseSettings[:facebook_app_id] = <ID_OF_YOUR_FB_APP>`
