### ISSUE TITLE
Test catarse.js local

### ISSUE THREAD

**Issue by caiotarifa** [catarse/catarse#2785]
Hi.

After `brew link`, the `//= require catarse.js/dist/catarse.js` still taking the `catarse.js` files from the `node_modules` folder instead of `bower_components`.

How can I fix it to test `catarse.js` local changes in development?

**Comment by caiotarifa** [comment]
I found a solution but I don't know if it is the best option.

In `application.rb`,  line `64`, just add `bower_components` asset path:

```
config.assets.paths << "#{Rails.root}/bower_components"
config.assets.paths << "#{Rails.root}/node_modules"
```

**Comment by vicnicius** [comment]
@caiotarifa you can run `npm link` on your catarse.js repo and then `npm link catarse.js` on your catarse repo. Bower is deprecated.

**Comment by caiotarifa** [comment]
Thanks, @vicnicius. I'll try.

What do you think about update _development_ section on [catarse.js](https://github.com/catarse/catarse.js)?

If you agree, I can submit a pull request.

**Comment by vicnicius** [comment]
If you have the time, please do it. We do need some help with the docs.
