### ISSUE TITLE
Tutorial Configuring Payment System

### ISSUE THREAD

**Issue by bonafernando** [catarse/catarse#2808]
I have cloned tag v2.0.
I've been working on it for 3 weeks and I'm having trouble configuring any Payment system.
I have tried Pagar.me and MoIP, but there is something missing and could't find the on the documentation how to make it work properly.
I've tried everything I could. I have even tried to Wireshark the API calls to understand what was going on.
Right now I have stopped on a message that shows after submitting the payment 
It says:
```
Verifique os dados informados
"value" is required,
```
![image](https://user-images.githubusercontent.com/2565620/31361930-5d0be22e-ad2c-11e7-956b-a32fa76b6d38.png)

Please, can anyone help me?

Thank you.

**Comment by adrianob** [comment]
Hi @bonafernando 
tag 2.0 is really old and unmantained, I would recommend using the master branch if possible.
MoIP is also not supported anymore, but pagarme should be working fine.
Have you set the keys properly on the settings table? Please post the rails server output when you try to create a payment, it seems that the contribution value is not being sent properly for some reason.

**Comment by bonafernando** [comment]
Thank you for the quick answer @adrianob 
Do you recommend to keep always on master or any other tag?

The rails output seems completely normal. I believe something about the payment system have changed.
![image](https://user-images.githubusercontent.com/2565620/31363207-2f439aba-ad33-11e7-8f4e-e574c8db84b3.png)

**Comment by bonafernando** [comment]
@adrianob 

For testing I have used some values on the payment configurations that might be the couse of this error, could you check?

![image](https://user-images.githubusercontent.com/2565620/31363903-1aa14828-ad38-11e7-8db0-65d44a6fb3cb.png)

```json
{
  pagarme_api_key: "xxxx",
  pagarme_encryption_key: "xxxx",
  pagarme_slip_tax: "1",
  pagarme_credit_card_tax: "1",
  pagarme_interest_rate: "1",
  pagarme_cents_fee: "1",
  pagarme_max_installments: "10",
  pagarme_minimum_value_for_installment: "1",
  cielo_tax: "1",
  stone_tax: "1",
  cielo_installment_diners_tax: "1",
  cielo_installment_not_diners_tax: "1",
  cielo_installment_amex_tax: "1",
  cielo_installment_not_amex_tax: "1"
}
``` 
The `xxxx` value is the correct key.

**Comment by bonafernando** [comment]
@adrianob I've just cloned master followed all the steps and remembered why I decided to go for an older version. 

I just couldn't go thru the basic setup:

![image](https://user-images.githubusercontent.com/2565620/31367608-cb642c46-ad4e-11e7-8fa3-9c4b1f70ba00.png)

**Comment by adrianob** [comment]
bower is deprecated, run ```npm install``` instead.

**Comment by adrianob** [comment]
Those settings should be fine, which version of catarse_pagarme are you using? If you need to run 2.0 tag you should use an older version or it won't be compatible.

**Comment by bonafernando** [comment]
The tag v2.0 of Catarse uses as default catarse_pagarme version 2.6.10: https://github.com/catarse/catarse/blob/v2.0/Gemfile#L41

About the `npm install` inside the folder node_modules, can I send a pull request updating the README.md to make it more clear?

**Comment by adrianob** [comment]
@bonafernando sure, any help with the documentation is appreciated. 
Btw, you should run ```npm install``` on the project's root folder.

**Comment by bonafernando** [comment]
Ohh, but that's what I did. And I was still having that error:
```
Sprockets::FileNotFound at /
couldn't find file 'mithril/mithril.min.js' with type 'application/javascript'
```
But now, after trying to run `npm install` on sub folders it is not working on the root directory.
```
$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json catarse.js@1.0.41 No repository field.
```
```
$ ls -lha | grep package
-rw-rw-r--  1 bona bona  238 Out  9 21:00 package.json
-rw-rw-r--  1 bona bona 161K Out  9 20:59 package-lock.json
```
```
$ npm --version
1.3.10
```
Is there a minimum requires version of npm to run catarse?

Also about the tag v2.0 (that I already have some work on it), do you think there is any easy way to make the payment system work. Also I tried to use MoIP, but I think there might be some configuration missing on my side. Do you have any clue on how to change from Pagar.me to MoIP on v2.0?

**Comment by bonafernando** [comment]
@adrianob , I have deleted the node_modules folder and rerun `npm install` and still having this error.

![image](https://user-images.githubusercontent.com/2565620/31389848-a4c8a4f4-ada8-11e7-9331-17e791553af7.png)

I'm in a very big doubt if I migrate all my work to this version on master or if I try to fix the compatibility of the payment system of the tag v2.0. I think I should give a last shot with MoIP, but I'm not sure how to configure it and make it work. This tutorial on Wiki looks very incomplete (https://github.com/catarse/catarse/wiki/System-Wide-Configurations#payment-gateways). Can you help me?

**Comment by adrianob** [comment]
@bonafernando I doubt MoIP will work without modifications, even on tag 2.0 it wasn't being used for a long time. 
There should be no problem in using pagarme with v2.0. I'm not sure why it isn't working for you but you could try running the catarse_pagarme gem locally and debug it to see what's going on.

**Comment by adrianob** [comment]
In particular see what's being return on this method: https://github.com/catarse/catarse_pagarme/blob/master/app/models/catarse_pagarme/payment_delegator.rb#L52

**Comment by bonafernando** [comment]
```
    def value_for_transaction
      puts
      puts
      puts
      puts "self.payment.value = #{self.payment.value}"
      puts "(self.payment.value * 100).to_i = #{(self.payment.value * 100).to_i}"
      puts
      puts
      puts
      (self.payment.value * 100).to_i
    end
```
Log:
```


self.payment.value = 10.0
(self.payment.value * 100).to_i = 1000



```

The error is still happening...

![image](https://user-images.githubusercontent.com/2565620/31401228-af66fc88-adc8-11e7-8249-2cccb207bfdd.png)

I have also add a `puts e.backtrace` at: https://github.com/catarse/catarse_pagarme/blob/v2.6.10/app/controllers/catarse_pagarme/credit_cards_controller.rb#L9
And this is the beginning of it:
```
pagarme-1.10.0/lib/pagarme/request.rb:56:in `rescue in run'
pagarme-1.10.0/lib/pagarme/request.rb:35:in `run'
pagarme-1.10.0/lib/pagarme/model.rb:23:in `create'
pagarme-1.10.0/lib/pagarme/transaction_common.rb:17:in `create'
pagarme-1.10.0/lib/pagarme/transaction.rb:16:in `charge'
catarse_pagarme-2.6.10/app/models/catarse_pagarme/credit_card_transaction.rb:8:in `charge!'
catarse_pagarme-2.6.10/app/controllers/catarse_pagarme/credit_cards_controller.rb:5:in `create'
actionpack-4.1.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack-4.1.10/lib/abstract_controller/base.rb:189:in `process_action'
```

Any other clue?

**Comment by adrianob** [comment]
@bonafernando pagarme has multiple API versions, make sure your account is using the correct one (should be the first version).

**Comment by bonafernando** [comment]
@adrianob, digging deeper I found the http response from Pagar.me:

```
{"errors":[{"type":"validation_error","parameter_name":"billing","message":"\"value\" is required"}],"url":"/transactions","method":"post"}
```

Also searching for the api path:
```
PagarMe.full_api_url(self.path) = https://api.pagar.me/1/transactions/calculate_installments_amount
```

Is this the path for the first version?

**Comment by bonafernando** [comment]
![image](https://user-images.githubusercontent.com/2565620/31402391-45b73a6a-adcc-11e7-9302-97634872abd2.png)
Should I ask to the support team of Pagar.me to use an older version?

**Comment by adrianob** [comment]
It's worth a try. We are at the 2013 version.

**Comment by bonafernando** [comment]
@adrianob in parallel of asking permission for the api, I have tracked the PAYLOAD, and it seems kind of wierd. Can you check if it is right?
PAYLOAD:
```
self.class.encode(parameters) = payment_method=credit_card&amount=1000&postback_url=https%3A%2F%2Fwww.catarse.me%3A3000%2Fpt%2Fpayment%2Fpagarme%2Fipn&installments=1&customer[email]=email%40gmail.com&customer[name]=NAME+LAST+NAME&metadata[key]=THE_KEY&metadata[project_id]=1&card_hash=A_BIG_HASH&status=local&card_number=&card_holder_name=&card_expiration_year=&card_expiration_month=&card_cvv=&api_key=MY_KEY
```
Thanks.

**Comment by bonafernando** [comment]
@adrianob, thanks for all your help.

After migrated to v2013-03-01 it started to work!

![image](https://user-images.githubusercontent.com/2565620/31411431-0313129e-ade8-11e7-8dee-1ca0734813e6.png)

The other error on the master branch about:
```
Sprockets::FileNotFound at /
couldn't find file 'mithril/mithril.min.js' with type 'application/javascript'
```
still without a fix but I'll close this issue as it's not related to the subject.
