### ISSUE TITLE
Updating `Projetos ja foram financiados por aqui` in `Comece seu projeto`

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2940]
Hi guys,

I am running a fork of Catarse in my own prod env. So far I have 1 successful project. 

Can you tell me how the value for `Projetos ja foram financiados por aqui` in `Comece seu projeto` page is updated ???

**Comment by adrianob** [comment]
If you mean the I18n it's located in ```config/locales/catarse_bootstrap/views/pages/start.pt.yml```.
If you mean the number of successful projects it comes from the "1".statistics materialized view, the job to refresh it automatically is defined in config/schedule.rb.

**Comment by sushant12** [comment]
i meant the latter.I did run `rake cron:refresh_materialized_views ` but the number was still not updated, however the other two values beside it were updated.

**Comment by adrianob** [comment]
Try running ```refresh materialized view CONCURRENTLY "1".statistics;``` directly on your DB, if it works it should be only a matter of setting up the refresh job properly.

**Comment by adrianob** [comment]
Btw it seems you are running an older version of catarse, since we don't have that cron job anymore... I don't remember if there were any bug fixes related to this, but it should be working on the latest version.

**Comment by sushant12** [comment]
@adrianob no problem. I am working on it

**Comment by sushant12** [comment]
@adrianob my apologies. I had commented out some rake cron commands.
