### ISSUE TITLE
Rails upgrading to 5.2 (question)

### ISSUE THREAD

**Issue by adilnaimi** [catarse/catarse#2981]
This isn't really an issue.

Is there any plan to upgrade to rails `5.2`?

**Comment by adrianob** [comment]
There are no plans since we are gradually moving away from Rails.
However any PRs in this regard would be welcomed.

**Comment by adilnaimi** [comment]
@adrianob thanks for your feedback

You mean by moving away from Rails to change to another web framework? which one?

**Comment by adilnaimi** [comment]
this issue/question can be closed
