### ISSUE TITLE
Redirection and category issue

### ISSUE THREAD

**Issue by WizardKid** [catarse/catarse#3009]
Hi i am using the current catarse as the one on catarse.me - my issue is that the "start your Project or Comece seu projeto" button is redirecting to https://crowdfunding.catarse.me/comece. I tried changing it to /start but that isnt helping. is there a way to keep it within my website or is there something i am missing? and my other issue is that categories not showing up in the dropdown nor anywhere on the website. Also when i login "i am getting this "pt/users/undefined/edit#balance" - undefined is on every link in the profile dropdown

**Comment by adrianob** [comment]
Did you insert any categories in the categories table?

**Comment by WizardKid** [comment]
Thank you for responding.. and the first solution cleared up the issue with the start project. I uploaded two screenshots so that you can get a better understanding of the issue as I can see anything in the log

**Comment by WizardKid** [comment]
The category table was populated in the migrate

**Comment by WizardKid** [comment]
The issues is that category is showing in the dropdown and whenever I logged it is showing undefined in the user paths

**Comment by adrianob** [comment]
It appears you didn't set the ```jwt_secret``` setting in the settings table.

**Comment by WizardKid** [comment]
![screenshot from 2018-05-23 17-20-52](https://user-images.githubusercontent.com/13104065/40437601-ad5340dc-5ead-11e8-8bb5-c7a808faad76.png)
i followed the instruction in the readme.. is there another setting for the jwt?

**Comment by adrianob** [comment]
@WizardKid are you working with the latest version? If you used our sample values from here https://github.com/common-group/services-core-db/blob/develop/sample.seed.sql jwt_secret should have a value of ```bUH75katNm6Yj0iPSchcgUuTwYAzZr7C```.

**Comment by WizardKid** [comment]
i am working with the latest version

**Comment by WizardKid** [comment]
should i execute this into the db? as i spent almost 6 hours getting this current db up

**Comment by adrianob** [comment]
Just update the jwt settings like so ```update settings set value = 'bUH75katNm6Yj0iPSchcgUuTwYAzZr7C' where name = 'jwt_secret';```

**Comment by adrianob** [comment]
I'm not sure where you came up with the current value in the first place, if you used this anywhere else it should be updated too.

**Comment by WizardKid** [comment]
Started GET "/pt/users/undefined/edit" for 127.0.0.1 at 2018-05-23 17:36:46 +0100
  [1m[36mBannedIp Exists (0.7ms)[0m  [1mSELECT  1 AS one FROM "banned_ips" WHERE "banned_ips"."ip" = $1 LIMIT 1[0m  [["ip", "127.0.0.1"]]
  [1m[35mBannedIp Exists (0.5ms)[0m  SELECT  1 AS one FROM "banned_ips" WHERE "banned_ips"."ip" = $1 LIMIT 1  [["ip", "127.0.0.1"]]
Processing by UsersController#edit as HTML
  Parameters: {"id"=>"undefined", "locale"=>"pt"}
  [1m[36mUser Load (1.0ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."deactivated_at" IS NULL AND "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1[0m  [["id", 0]]
  Rendered catarse_bootstrap/devise/shared/_header.html.slim (9.1ms)
  Rendered catarse_bootstrap/errors/not_found.html.slim within layouts/catarse_bootstrap (1309.9ms)

**Comment by WizardKid** [comment]
this is the current log

**Comment by WizardKid** [comment]
anyone can help with this issue.. i have tried everything to get this working

**Comment by WizardKid** [comment]
the below image summaries the issue i am having
![screenshot from 2018-05-26 12-15-46](https://user-images.githubusercontent.com/13104065/40575561-0e90a726-60df-11e8-9de0-e144609c0509.png)
this is the catarse user path which assigns numbers to the user paths
![screenshot from 2018-05-26 12-16-18](https://user-images.githubusercontent.com/13104065/40575571-3b7f5aca-60df-11e8-8095-3118bb477871.png)
this is my website showing undefined

**Comment by WizardKid** [comment]
Solved

**Comment by erickbrenes07** [comment]
Hi @WizardKid, how did you solved the undefined user problem, Im having the same issue.

**Comment by jcserracampos** [comment]
Hey, @WizardKid, come back!
