### ISSUE TITLE
Country Dropdown tab and campaign amount error

### ISSUE THREAD

**Issue by WizardKid** [catarse/catarse#3021]
Hi I seem to be having some issues with the country dropdown selection. it isn't populating any values
![country](https://user-images.githubusercontent.com/13104065/40890427-bee5f43e-676d-11e8-9b46-e3cefe127755.PNG)

and also if I should enter the project amount the comma isn't remaining in the correct place (see img)
![capture](https://user-images.githubusercontent.com/13104065/40890437-ea5f2806-676d-11e8-8e76-4342a7058a91.PNG)
![capture1](https://user-images.githubusercontent.com/13104065/40890438-ea7a1ef4-676d-11e8-85ec-ae415503ab9f.PNG)
eg. if I want to input 35,000 I would get this: 350.00,00 and if I delete the numbers I would receive a comma
can anyone provide any information on how to solve this issue

**Comment by WizardKid** [comment]
thank you very much.. can you point to the locations of these hardcodes so I make these changes.. I have worked single handed on this website so it should be a walk in the park (www.oppostarter.com)

**Comment by adrianob** [comment]
I don't know off the top of my head but you'll probably need to update the input standard both on rails and on mithril components that use them.

**Comment by WizardKid** [comment]
ok

**Comment by WizardKid** [comment]
Thank you very much

**Comment by WizardKid** [comment]
hi @adrianob I have reopen this issue as the country tab still not resolved. Also while searching through the files for the currency fix I found this in .\node_modules\catarse.js\src\c\project-goal-edit-card.js 
"monetaryToFloat = (propValue: Function): number => {
        if (_.isNumber(propValue())) {
            return parseFloat(propValue());
        }

        return parseFloat(propValue().replace('.', '').replace(',', '.'));
    },

    applyMonetaryMask = (number: number): string => {
        let onlyNumbers = String(number).replace(/[^0-9]|[.]/g, ''),
            integerPart = onlyNumbers.slice(0, onlyNumbers.length - 2),
            decimalPart = onlyNumbers.slice(onlyNumbers.length - 2);

        integerPart = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, '.');

        return `${integerPart},${decimalPart}`;"

can you explain what this code do?

**Comment by adrianob** [comment]
@WizardKid I believe this overrides the default browser numeric field to use the brazilian standard. Also, if you want to modify any mithril files you should clone the catarse.js repo and ```npm link``` them instead of editing from node_modules directly.

**Comment by WizardKid** [comment]
ok thank you.. I cant seem to find the direct string to the currency
