### ISSUE TITLE
Is it possialbe any expert of catarse to provide a Docker.io version installation?

### ISSUE THREAD

**Issue by 9cat** [catarse/catarse#889]
Is it possialbe any expert of catarse to provide a Docker.io version installation?

It is much easier to provider people distribute your solution.

**Comment by pinak1180** [comment]
Hey, i tried to integrate docker for catarse though it is not complete but can you general idea.

this is my fork you can check it out there.

https://github.com/pinak1180/catarse

**Comment by devton** [comment]
@9cat we are working on this ;)

**Comment by finkiki** [comment]
waiting for this

**Comment by igordcsouza** [comment]
someone still working on this?

**Comment by kurenn** [comment]
I'm working on this, I've made a lot of progress, you can see the progress here: https://github.com/IcaliaLabs/catarse , branch: `feat/dockerization`

**Comment by vicnicius** [comment]
Closing the issue as docker support is now provided.
