### ISSUE TITLE
Run catarse through port 80

### ISSUE THREAD

**Issue by sveralex** [catarse/catarse#988]
Hi.
I successfully installed Catarse on linux. 
All things work well, except `channel` links in admin menu, but it is not so important.
The problem is, that
I failed to start catarse on a standard http port, rather than 3000 !
When I run

#rails server -e production --port=80
or
#ENABLE_HTTPS=yes rails s -e production --port=80

I get:

Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:80, CTRL+C to stop
Exiting
/home/.../.rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
from /home/.../.rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_server'
...

Of course, I googled all topics on this matter, but did not find any reliable decision.

Can anybody help me to make it work on port 80 ?
Should I add/change something in /etc hosts, or execute any commands, or modify some config files.
Please advice

**Comment by mulysatest** [comment]
Sorry for out of topic but just curious about how to fix this problem https://github.com/catarse/catarse/issues/994

**Comment by devton** [comment]
@sveralex @mulysatest the port 80 in some cases is already used by apache or another default webserver. to put on production server try some of this links:
https://gorails.com/deploy/ubuntu/14.04
http://www.gotealeaf.com/blog/setting-up-your-production-server-with-nginx-and-unicorn
