### ISSUE TITLE
Initial Setup issue?

### ISSUE THREAD

**Issue by MasterDev21** [catarse/catarse#994]
Hey I'm getting an "Internal server error" when I first start the rails server. 
I'm running Ubuntu 13.10
In the terminal it says:

Unexpected error while processing request: Missing `secret_key_base` for 'development' environment, set this value in `config/secrets.yml`

Any Ideas?

**Comment by mulysatest** [comment]
same

**Comment by MasterDev21** [comment]
Not at all.  Couldn't really find much help either.  Let me know if you have any success.

**Comment by mulysatest** [comment]
Finally, I managed to solve the problem. You would like to know please kindly exchange knowledge with me with Skype: asylu3

**Comment by devton** [comment]
@MasterDev21  @mulysatest I think that you need to configure the config/initializers/secret_token.rb

**Comment by andbod** [comment]
I had the same problem and was related with the command : 
bundle exec rake db:migrate
It was returing an error since of a missing Postgres library
Solved (on Debian) by issuing this command before db:migrate : 
apt-get install postgresql-contrib
